/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-03 07:45:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.health;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class health_005ffood_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Welcome EasyET</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: MyBiz - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Top Bar ======= -->\r\n");
      out.write("  <section id=\"topbar\" class=\"d-none d-lg-block\">\r\n");
      out.write("    <div class=\"container d-flex\">\r\n");
      out.write("      <div class=\"contact-info mr-auto\">\r\n");
      out.write("        <i class=\"icofont-envelope\"></i><a href=\"mailto:contact@example.com\">chk4814@naver.com</a>\r\n");
      out.write("        <i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("      \t ");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/login_form.jsp\" >LOGIN</a> \r\n");
      out.write("      \t \t<a href=\"/join/join_form.jsp\" >JOIN</a>\r\n");
      out.write("    \t  ");

      	}
      	else
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/logout_action.jsp\" >LOGOUT</a> \r\n");
      out.write("      \t \t<a href=\"/mypage/mypage.jsp\" >MYPAGE</a>\r\n");
      out.write("    \t  ");

      	}
      
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo mr-auto\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"/index.jsp\">Easy<span>ET</span></a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"/health/health.jsp\">건강정보</a></li>\r\n");
      out.write("          <li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\r\n");
      out.write("          <li class=\"drop-down\"><a href=\"\">Board</a>\r\n");
      out.write("          \t<ul>\r\n");
      out.write("          \t\t<li><a href=\"/board/board_list.jsp\">소통 게시판</a></li>\r\n");
      out.write("          \t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\r\n");
      out.write("          \t</ul>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav><!-- .nav-menu -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");

  	//session.setAttribute("ss","test@naver.com");
	String ss = session.getAttribute("ss").toString();
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("  <br><br>\r\n");

	request.setCharacterEncoding("utf-8");
	String url = request.getParameter("url");
	response.sendRedirect(url);

      out.write("\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("              <h3>EasyET</h3>\r\n");
      out.write("              <p>\r\n");
      out.write("                                    경기도 부천시 경인로 590 <br>\r\n");
      out.write("                <strong>Phone:</strong> +82 02-2610-0600<br>\r\n");
      out.write("                <strong>Email:</strong> chk4814@naver.com<br>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6 footer-links\">\r\n");
      out.write("            <h4>사이트맵</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("              \t<a href=\"/index.jsp\">Home</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/health/health.jsp\">건강정보</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/board/board_list.jsp\">소통게시판</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp&nbsp\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        &copy; Copyright <strong><span>MyBiz</span></strong>. All Rights Reserved\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"credits\">\r\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\r\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\r\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
