/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-03 04:50:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.health;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class health_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Welcome EasyET</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: MyBiz - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script >\r\n");
      out.write("\r\n");
      out.write("function jumpMenu(frm){\r\n");
      out.write("\tlocation.href=frm.jump.options[frm.jump.selectedIndex].value;\r\n");
      out.write("\tfrm.jump.selectedIndex.selected;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function input_Text(){\r\n");
      out.write("\tvar totalbodywater = document.getElementById('totalbodywater').value;\r\n");
      out.write("\tvar protein = document.getElementById('protein').value;\r\n");
      out.write("\tvar mineral = document.getElementById('mineral').value;\r\n");
      out.write("\tvar bodyfat = document.getElementById('bodyfat').value;\r\n");
      out.write("\tvar weight = document.getElementById('weight').value;\r\n");
      out.write("\tweight.value = Number(totalbodywater.value) + Number(protein.value) + Number(mineral.value) + Number(bodyfat.value);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Chking() {\r\n");
      out.write("    var f = eval(\"document.inbody_form\");\r\n");
      out.write("    if(f.totalbodywater.value && f.protein.value && f.mineral.value && f.bodyfat.value) {\r\n");
      out.write("        f.weight.value = (parseFloat(f.totalbodywater.value) + parseFloat(f.protein.value) + parseFloat(f.mineral.value) + parseFloat(f.bodyfat.value)).toFixed(2);\r\n");
      out.write("    } else {\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function inbodyCheck() {\r\n");
      out.write("    var inbody = document.inbody_form;\r\n");
      out.write("    \r\n");
      out.write("    var regex = /^[0-9]*$/;\r\n");
      out.write("    var regex_integer = /^[0-9]*[.][0-9]*$/\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    if(inbody['height'].value != \"\")\r\n");
      out.write("    {\r\n");
      out.write("    \tif(regex.test(inbody['height'].value) == true || regex_integer.test(inbody['height'].value) == true)\r\n");
      out.write("    \t{\r\n");
      out.write("    \t\tif(inbody['age'].value != \"\")\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t\tif(regex.test(inbody['age'].value) == true)\r\n");
      out.write("    \t\t\t{\r\n");
      out.write("    \t\t\t\tif(inbody['totalbodywater'].value != \"\")\r\n");
      out.write("    \t\t\t\t{\r\n");
      out.write("    \t\t\t\t\tif(regex.test(inbody['totalbodywater'].value) == true || regex_integer.test(inbody['totalbodywater'].value) == true)\r\n");
      out.write("    \t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\tif(inbody['protein'].value != \"\")\r\n");
      out.write("    \t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\tif(regex.test(inbody['protein'].value) == true || regex_integer.test(inbody['protein'].value) == true)\r\n");
      out.write("    \t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\tif(inbody['mineral'].value != \"\")\r\n");
      out.write("    \t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\tif(regex.test(inbody['mineral'].value) == true || regex_integer.test(inbody['mineral'].value) == true)\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\tif(inbody['bodyfat'].value != \"\")\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\tif(regex.test(inbody['bodyfat'].value) == true || regex_integer.test(inbody['bodyfat'].value) == true)\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\tif(inbody['weight'].value != \"\")\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\tif(regex.test(inbody['weight'].value) == true || regex_integer.test(inbody['weight'].value) == true)\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\tif(inbody['skeletal_muscle_mass'].value != \"\")\r\n");
      out.write("    \t    \t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif(regex.test(inbody['skeletal_muscle_mass'].value) == true || regex_integer.test(inbody['skeletal_muscle_mass'].value) == true)\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\treturn true;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"골격근량은 정수나 소수만 가능합니다.\");\r\n");
      out.write("        \t    \t    \t    \t    \t    \t    \t    \tinbody['skeletal_muscle_mass'].focus();\r\n");
      out.write("        \t    \t    \t    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t    \t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"골격근량을 입력해주세요. 골격근량은 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t    \t    \t    \t    \t    \t    \t    \tinbody['skeletal_muscle_mass'].focus();\r\n");
      out.write("    \t    \t    \t    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"체중은 정수나 소수만 가능합니다.\");\r\n");
      out.write("        \t    \t    \t    \t    \t    \t    \tinbody['weight'].focus();\r\n");
      out.write("        \t    \t    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t\talert(\"체중을 입력해주세요. 체중은 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t    \t    \t    \t    \t    \t    \tinbody['weight'].focus();\r\n");
      out.write("    \t    \t    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\talert(\"체지방량은 정수나 소수만 가능합니다.\");\r\n");
      out.write("        \t    \t    \t    \t    \t    \tinbody['bodyfat'].focus();\r\n");
      out.write("        \t    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\talert(\"체지방량을 입력해주세요. 체지방량은 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t    \t    \t    \t    \t    \tinbody['bodyfat'].focus();\r\n");
      out.write("    \t    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\talert(\"무기질은 정수나 소수만 가능합니다.\");\r\n");
      out.write("        \t    \t    \t    \t    \tinbody['mineral'].focus();\r\n");
      out.write("        \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\t\talert(\"무기질을 입력해주세요. 무기질은 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t    \t    \t    \t    \tinbody['mineral'].focus();\r\n");
      out.write("    \t    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\t\talert(\"단백질은 정수나 소수만 가능합니다.\");\r\n");
      out.write("        \t    \t    \t    \tinbody['protein'].focus();\r\n");
      out.write("        \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\talert(\"단백질을 입력해주세요. 단백질은 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t    \t    \t    \tinbody['protein'].focus();\r\n");
      out.write("    \t    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\telse\r\n");
      out.write("    \t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\talert(\"체수분은 정수나 소수만 가능합니다.\");\r\n");
      out.write("        \t    \t    \tinbody['totalbodywater'].focus();\r\n");
      out.write("        \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\telse\r\n");
      out.write("    \t\t\t\t{\r\n");
      out.write("    \t\t\t\t\talert(\"체수분을 입력해주세요. 체수분은 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t    \t    \tinbody['totalbodywater'].focus();\r\n");
      out.write("    \t    \t\t    return false;\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\telse\r\n");
      out.write("    \t\t\t{\r\n");
      out.write("    \t\t\t\talert(\"나이는 정수만 가능합니다.\");\r\n");
      out.write("        \t    \tinbody['age'].focus();\r\n");
      out.write("        \t\t    return false;\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\telse\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t\talert(\"나이를 입력해주세요. 나이는 정수만 가능합니다.\");\r\n");
      out.write("    \t    \tinbody['age'].focus();\r\n");
      out.write("    \t\t    return false;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \telse\r\n");
      out.write("    \t{\r\n");
      out.write("    \t\talert(\"키는 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \t\tinbody['height'].focus();\r\n");
      out.write("    \t    return false;\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("    \talert(\"키를 입력해주세요. 키는 정수나 소수만 가능합니다.\");\r\n");
      out.write("    \tinbody['height'].focus();\r\n");
      out.write("\t    return false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Top Bar ======= -->\r\n");
      out.write("  <section id=\"topbar\" class=\"d-none d-lg-block\">\r\n");
      out.write("    <div class=\"container d-flex\">\r\n");
      out.write("      <div class=\"contact-info mr-auto\">\r\n");
      out.write("        <i class=\"icofont-envelope\"></i><a href=\"mailto:contact@example.com\">chk4814@naver.com</a>\r\n");
      out.write("        <i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("      \t ");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/login_form.jsp\" >LOGIN</a> \r\n");
      out.write("      \t \t<a href=\"/join/join_form.jsp\" >JOIN</a>\r\n");
      out.write("    \t  ");

      	}
      	else
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/logout_action.jsp\" >LOGOUT</a> \r\n");
      out.write("      \t \t<a href=\"/mypage/mypage.jsp\" >MYPAGE</a>\r\n");
      out.write("    \t  ");

      	}
      
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo mr-auto\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"/index.jsp\">Easy<span>ET</span></a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"/health/health.jsp\">건강정보</a></li>\r\n");
      out.write("          <li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\r\n");
      out.write("          <li class=\"drop-down\"><a href=\"\">Board</a>\r\n");
      out.write("          \t<ul>\r\n");
      out.write("          \t\t<li><a href=\"/board/board_list.jsp\">소통 게시판</a></li>\r\n");
      out.write("          \t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\r\n");
      out.write("          \t</ul>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav><!-- .nav-menu -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("  \r\n");
      out.write("<script >\r\n");
      out.write("function jumpMenu(frm){\r\n");
      out.write("\tlocation.href=frm.jump.options[frm.jump.selectedIndex].value;\r\n");
      out.write("\tfrm.jump.selectedIndex.selected;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("  \r\n");
      out.write("  ");

  	//session.setAttribute("ss","test@naver.com");
	String ss = session.getAttribute("ss").toString();
	String myid = null;
	String myname = null;
	
	String date = request.getParameter("date");
	//int member_uid = Integer.parseInt(request.getParameter("uid"));
	//String updateIdentify_1 = ss.replaceAll("@", "");
	//String updateIdentify_2 = updateIdentify_1.replace(".", "");
	//String table_name = updateIdentify_2 + "_member_inbody";
	
	
	//이건 인바디변수
	int inbody_uid = 0;
	String name = null;
	int sex = 0;
	int age = 0;
	Timestamp check_date = new Timestamp(System.currentTimeMillis());
	float totalbodywater = 0;
	float protein = 0;
	float mineral = 0; 
	float bodyfat = 0;
	float height = 0;
	float weight = 0;
	float skeletal_muscle_mass = 0; 
	float bmi = 0; 
	float percentbodyfat = 0; 
	int leftarm_muscle = 0; 
	int rightarm_muscle = 0; 
	int leftleg_muscle = 0; 
	int rightleg_muscle = 0; 
	int center_muscle = 0;
	int leftarm_fat = 0;
	int leftleg_fat = 0;
	int rightarm_fat = 0;
	int rightleg_fat = 0;
	int center_fat = 0;
	
	Timestamp today = new Timestamp(System.currentTimeMillis());
	Timestamp getdatefromboard = new Timestamp(System.currentTimeMillis());
	getdatefromboard = Timestamp.valueOf("1900-01-01 00:00:00.0");
	java.text.SimpleDateFormat today_date_format = new java.text.SimpleDateFormat("yyyy-MM-dd");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".contact  {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  box-shadow: 0 0 24px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("  padding: 30px;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .form-group {\r\n");
      out.write("  padding-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .validate {\r\n");
      out.write("  display: none;\r\n");
      out.write("  color: red;\r\n");
      out.write("  margin: 0 0 15px 0;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .error-message {\r\n");
      out.write("  display: none;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background: #ed3c0d;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .error-message br + br {\r\n");
      out.write("  margin-top: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .sent-message {\r\n");
      out.write("  display: none;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background: #18d26e;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .loading {\r\n");
      out.write("  display: none;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .loading:before {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  width: 24px;\r\n");
      out.write("  height: 24px;\r\n");
      out.write("  margin: 0 10px -6px 0;\r\n");
      out.write("  border: 3px solid #18d26e;\r\n");
      out.write("  border-top-color: #eee;\r\n");
      out.write("  -webkit-animation: animate-loading 1s linear infinite;\r\n");
      out.write("  animation: animate-loading 1s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact  input, .contact textarea {\r\n");
      out.write("  border-radius: 0;\r\n");
      out.write("  box-shadow: none;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact input {\r\n");
      out.write("  height: 44px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact textarea {\r\n");
      out.write("  padding: 10px 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact button[type=\"submit\"] {\r\n");
      out.write("  background: #01b1d7;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  padding: 10px 24px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  transition: 0.4s;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact  button[type=\"submit\"]:hover {\r\n");
      out.write("  background: #0dd3fe;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("  <br><br>\r\n");
      out.write("  \t<div class=\"container contact\">\r\n");
      out.write("  \t<form name=\"inbody_form\" method=\"post\" action=\"/health/health_action.jsp\" onsubmit=\"return inbodyCheck();\">\r\n");
      out.write("  \t\t<div class=\"row content\">\r\n");
      out.write("  \t\t\t<div class=\"col-lg-6\"><h2>InBody 작성하기</h2></div></div><br><br>\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("                   <table class=\"table table-hover table-striped\" style=\"width: 100%\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>아이디<br><input type=\"text\" id=\"inbody_uid\" name=\"inbody_uid\" class=\"form-control input-shadow\" value=\"");
      out.print(ss );
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("                    \t\t<td>신장(cm)<br><input type=\"text\" id=\"height\" name=\"height\" class=\"form-control input-shadow\" placeholder=\"cm\"></td>\r\n");
      out.write("                    \t\t<td>연령<br><input type=\"text\" id=\"age\" name=\"age\" class=\"form-control input-shadow\"></td>\r\n");
      out.write("                    \t\t<td>성별<br>\r\n");
      out.write("                    \t\t\t<select name=\"sex\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\" >남성</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\" >여성</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td>검사일시<br><input type=\"text\" id=\"check_date\" name=\"check_date\" class=\"form-control input-shadow\" value=\"");
      out.print(check_date );
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                    <h4>체성분분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체수분(L)</td><td><input type=\"text\" id=\"totalbodywater\" name=\"totalbodywater\" class=\"form-control input-shadow\" onKeyPress=\"Chking();\" onKeyUp=\"Chking();\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>단백질(kg)</td><td><input type=\"text\" id=\"protein\" name=\"protein\" class=\"form-control input-shadow\" onKeyPress=\"Chking();\" onKeyUp=\"Chking();\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>무기질(kg)</td><td><input type=\"text\" id=\"mineral\" name=\"mineral\" class=\"form-control input-shadow\" onKeyPress=\"Chking();\" onKeyUp=\"Chking();\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체지방량(kg)</td><td><input type=\"text\" id=\"bodyfat\" name=\"bodyfat\" class=\"form-control input-shadow\" onKeyPress=\"Chking();\" onKeyUp=\"Chking();\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                    <h4>골격근 지방 분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td></td><td>측정치</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체중(kg)</td><td><input type=\"text\" id=\"weight\" name=\"weight\" class=\"form-control input-shadow\" onclick=\"input_Text();\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>골격근량(kg)</td><td><input type=\"text\" id=\"skeletal_muscle_mass\" name=\"skeletal_muscle_mass\" class=\"form-control input-shadow\"></td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                    <h4>부위별 분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">부위별근육분석</td>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">부위별체지방분석</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>왼팔근육\r\n");
      out.write("                    \t\t\t<select name=\"leftarm_muscle\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른팔근육\r\n");
      out.write("                    \t\t\t<select name=\"rightarm_muscle\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td>왼팔지방\r\n");
      out.write("                    \t\t\t<select name=\"leftarm_fat\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른팔지방\r\n");
      out.write("                    \t\t\t<select name=\"rightarm_fat\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">복부근육\r\n");
      out.write("                    \t\t\t<select name=\"center_muscle\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">복부지방\r\n");
      out.write("                    \t\t\t<select name=\"center_fat\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>왼다리근육\r\n");
      out.write("                    \t\t\t<select name=\"leftleg_muscle\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른다리근육\r\n");
      out.write("                    \t\t\t<select name=\"rightleg_muscle\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td>왼다리지방\r\n");
      out.write("                    \t\t\t<select name=\"leftleg_fat\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른다리지방\r\n");
      out.write("                    \t\t\t<select name=\"rightleg_fat\" class=\"form-control input-shadow\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"0\">평균이하</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1\">평균</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"2\">평균이상</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                   \r\n");
      out.write("                        \t\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"text-center\"><button type=\"submit\">작성완료</button></div>\r\n");
      out.write("                    </form>\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("              <h3>EasyET</h3>\r\n");
      out.write("              <p>\r\n");
      out.write("                                    경기도 부천시 경인로 590 <br>\r\n");
      out.write("                <strong>Phone:</strong> +82 02-2610-0600<br>\r\n");
      out.write("                <strong>Email:</strong> chk4814@naver.com<br>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6 footer-links\">\r\n");
      out.write("            <h4>사이트맵</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("              \t<a href=\"/index.jsp\">Home</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/health/health.jsp\">건강정보</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/board/board_list.jsp\">소통게시판</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp&nbsp\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        &copy; Copyright <strong><span>MyBiz</span></strong>. All Rights Reserved\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"credits\">\r\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\r\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\r\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
