/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-11-20 13:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.health;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class health_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Welcome EasyET</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: MyBiz - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Top Bar ======= -->\r\n");
      out.write("  <section id=\"topbar\" class=\"d-none d-lg-block\">\r\n");
      out.write("    <div class=\"container d-flex\">\r\n");
      out.write("      <div class=\"contact-info mr-auto\">\r\n");
      out.write("        <i class=\"icofont-envelope\"></i><a href=\"mailto:contact@example.com\">chk4814@naver.com</a>\r\n");
      out.write("        <i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("      \t ");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/login_form.jsp\" >LOGIN</a> \r\n");
      out.write("      \t \t<a href=\"/join/join_form.jsp\" >JOIN</a>\r\n");
      out.write("    \t  ");

      	}
      	else
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/logout_action.jsp\" >LOGOUT</a> \r\n");
      out.write("      \t \t<a href=\"/mypage/mypage.jsp\" >MYPAGE</a>\r\n");
      out.write("    \t  ");

      	}
      
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo mr-auto\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"/index.jsp\">Easy<span>ET</span></a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"/health/health.jsp\">건강정보</a></li>\r\n");
      out.write("          <li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\r\n");
      out.write("          <li class=\"drop-down\"><a href=\"\">Board</a>\r\n");
      out.write("          \t<ul>\r\n");
      out.write("          \t\t<li><a href=\"/board/board_list.jsp\">소통 게시판</a></li>\r\n");
      out.write("          \t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\r\n");
      out.write("          \t</ul>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav><!-- .nav-menu -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("  \r\n");
      out.write("<script >\r\n");
      out.write("function jumpMenu(frm){\r\n");
      out.write("\tlocation.href=frm.jump.options[frm.jump.selectedIndex].value;\r\n");
      out.write("\tfrm.jump.selectedIndex.selected;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".contact  {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  box-shadow: 0 0 24px 0 rgba(0, 0, 0, 0.12);\r\n");
      out.write("  padding: 30px;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .form-group {\r\n");
      out.write("  padding-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .validate {\r\n");
      out.write("  display: none;\r\n");
      out.write("  color: red;\r\n");
      out.write("  margin: 0 0 15px 0;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .error-message {\r\n");
      out.write("  display: none;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background: #ed3c0d;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .error-message br + br {\r\n");
      out.write("  margin-top: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .sent-message {\r\n");
      out.write("  display: none;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  background: #18d26e;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .loading {\r\n");
      out.write("  display: none;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact .loading:before {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  width: 24px;\r\n");
      out.write("  height: 24px;\r\n");
      out.write("  margin: 0 10px -6px 0;\r\n");
      out.write("  border: 3px solid #18d26e;\r\n");
      out.write("  border-top-color: #eee;\r\n");
      out.write("  -webkit-animation: animate-loading 1s linear infinite;\r\n");
      out.write("  animation: animate-loading 1s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact  input, .contact textarea {\r\n");
      out.write("  border-radius: 0;\r\n");
      out.write("  box-shadow: none;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact input {\r\n");
      out.write("  height: 44px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact textarea {\r\n");
      out.write("  padding: 10px 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact button[type=\"submit\"] {\r\n");
      out.write("  background: #01b1d7;\r\n");
      out.write("  border: 0;\r\n");
      out.write("  padding: 10px 24px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  transition: 0.4s;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact  button[type=\"submit\"]:hover {\r\n");
      out.write("  background: #0dd3fe;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("  <br><br>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" ");

      if(session.getAttribute("ss") == null)
      {
      	
      out.write("\r\n");
      out.write("    \t \t<div class=\"container contact\">\r\n");
      out.write("  \t\t\t\t<div class=\"row content\">\r\n");
      out.write("  \t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("  \t\t\t\t\t\t<h2>로그인 안내</h2>\r\n");
      out.write("  \t\t\t\t\t\t<h4>건강정보를 이용하려면 로그인이 필요합니다.<br><a href=\"/login/login_form.jsp\">로그인하러 가기</a></h4>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t</div>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("    \t");

      }
      else
      {
    		String ss = session.getAttribute("ss").toString();
    		String myid = null;
    		String myname = null;
    		
    		String date = request.getParameter("date");
    		
    		
    		//이건 인바디변수
    		int inbody_uid = 0;
    		String name = null;
    		int sex = 0;
    		int age = 0;
    		Timestamp check_date = new Timestamp(System.currentTimeMillis());
    		float totalbodywater = 0;
    		float protein = 0;
    		float mineral = 0; 
    		float bodyfat = 0;
    		float height = 0;
    		float weight = 0;
    		float skeletal_muscle_mass = 0; 
    		float bmi = 0; 
    		float percentbodyfat = 0; 
    		int leftarm_muscle = 0; 
    		int rightarm_muscle = 0; 
    		int leftleg_muscle = 0; 
    		int rightleg_muscle = 0; 
    		int center_muscle = 0;
    		int leftarm_fat = 0;
    		int leftleg_fat = 0;
    		int rightarm_fat = 0;
    		int rightleg_fat = 0;
    		int center_fat = 0;
    		
    		Timestamp today = new Timestamp(System.currentTimeMillis());
    		Timestamp getdatefromboard = new Timestamp(System.currentTimeMillis());
    		getdatefromboard = Timestamp.valueOf("1900-01-01 00:00:00.0");
    		java.text.SimpleDateFormat today_date_format = new java.text.SimpleDateFormat("yyyy-MM-dd");
    		
    			
    	
    	    		 Connection conn = null;
    	    		 PreparedStatement pstmt = null;
    	    		 ResultSet rs = null;
    	    		 String str = "";
    	    		 try{
    	    			 String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
    	    			 String dbId = "yhpj";
    	    			 String dbPass = "Yuhan2020!";
    	    		 	
    	    		 	Class.forName ("com.mysql.jdbc.Driver"); //driver load
    	    		 	conn = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
    	    		 	
    					str = "select id,name from member where id=?";
    	    		 	pstmt = conn.prepareStatement(str);
    	    		 	pstmt.setString(1,ss);
    	    		 	rs = pstmt.executeQuery();
    	    		 	
    	    		 	while(rs.next())
    	    		 	{
    	    		 		myid = rs.getString(1);
    	    		 		myname = rs.getString(2);
    	    		 	}
    	    		 	
    	    		 	
    	    		 

    	    		 }catch(Exception e){
    	    		 	e.printStackTrace();
    	    		 }finally{
    	    			if(rs !=null)
    	    					try{rs.close();}catch(SQLException sqle){}
    	    		 	if(pstmt != null)
    	    		 		try{pstmt.close();}catch(SQLException sqle){}
    	    		 	if(conn != null)
    	    		 		try{conn.close();}catch(SQLException sqle){}

    	    		 }
    	    
    	   
      out.write("\r\n");
      out.write("    \t   \t<div class=\"container contact\">\r\n");
      out.write("  \t<form name=\"inbody_form\" method=\"post\" action=\"health_action.jsp\" class=\"php-email-form\">\r\n");
      out.write("  \t\t<div class=\"row content\"><div class=\"col-lg-6\"><h2>InBody</h2></div></div>\r\n");
      out.write("  \t\t\r\n");
      out.write("                    <div align=\"right\">\r\n");
      out.write("                    \t<button type=\"button\" class=\"btn btn-light btn-block\" style=\"width:20%; background-color: #01b1d7; fon\" onclick=\"location.href='/health/health_form.jsp' \"><font color=\"white\">Inbody작성</font></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        \t");

    		 Connection conn1 = null;
    		 PreparedStatement pstmt1 = null;
    		 ResultSet rs1 = null;
    		 String strfirst = "";
    		 try{
    			 String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
    			 String dbId = "yhpj";
    			 String dbPass = "Yuhan2020!";
    		 	
    		 	Class.forName ("com.mysql.jdbc.Driver"); //driver load
    		 	conn1 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
    		 	
				strfirst = "select user_id from user where user_id=?";
    		 	pstmt1 = conn1.prepareStatement(strfirst);
    		 	pstmt1.setString(1,ss);
    		 	rs1 = pstmt1.executeQuery();
    		 	
    		 	while(rs1.next())
    		 	{
    		 		myid = rs1.getString(1);
    		 	}
    		 	
    		 	strfirst = "select check_date from inbody where name=? order by check_date desc";
    		 	pstmt1 = conn1.prepareStatement(strfirst);
    		 	pstmt1.setString(1,ss);
    		 	rs1 = pstmt1.executeQuery();
    		 	
    		 	
      out.write("\r\n");
      out.write("    \t\t \t\t<form name=\"forms\" method=\"post\" action=\"health.jsp\" >\r\n");
      out.write("          \t\t\t\t<select name=\"jump\" onChange=\"jumpMenu(this.form)\" class=\"form-control input-shadow\" style=\"width:30%;\">\r\n");
      out.write("            \t\t\t\t<option value=\"\" >날짜 선택</option>\r\n");
      out.write("\t    \t\r\n");
      out.write(" \r\n");
      out.write("\t    \r\n");
      out.write("\t\t \t\t");

    		 	
    		 	while(rs1.next())
    		 	{
    		 		
      out.write("\r\n");
      out.write("    \t\t \t\t<option value=\"health.jsp?date=");
      out.print(rs1.getTimestamp(1));
      out.write("\">\r\n");
      out.write("    \t\t \t\t\t");
      out.print(rs1.getTimestamp(1));
      out.write("\r\n");
      out.write("    \t\t \t\t</option>\r\n");
      out.write("    \t\t \t\t");

    		 	}
		 		
      out.write("\r\n");
      out.write("\t\t \t\t</select>\r\n");
      out.write("\t\t \t\t");

    		 	strfirst = "SELECT uid, NAME, sex, age, check_date, totalbodywater, protein, mineral, " +
    		 			"bodyfat, height, weight, skeletal_muscle_mass, bmi,percentbodyfat, leftarm_muscle, rightarm_muscle, leftleg_muscle, " +
    		 			"rightleg_muscle, center_muscle, leftarm_fat, leftleg_fat, rightarm_fat, rightleg_fat, center_fat " +
    		 			"FROM inbody WHERE name=? and check_date=?";
    		 	pstmt1 = conn1.prepareStatement(strfirst);
    		 	pstmt1.setString(1,ss);
    		 	pstmt1.setString(2, date);
    		 	rs1 = pstmt1.executeQuery();
    		 	
    		 	while(rs1.next())
    		 	{
    		 		inbody_uid = rs1.getInt(1);
    		 		name = rs1.getString(2);
    		 		sex = rs1.getInt(3);
    		 		age = rs1.getInt(4);
    		 		check_date = rs1.getTimestamp(5);
    		 		totalbodywater = rs1.getFloat(6);
    		 		protein = rs1.getFloat(7);
    		 		mineral = rs1.getFloat(8);
    		 		bodyfat = rs1.getFloat(9);
    		 		height = rs1.getFloat(10);
    		 		weight = rs1.getFloat(11);
    		 		skeletal_muscle_mass = rs1.getFloat(12);
    		 		bmi = rs1.getFloat(13);
    		 		percentbodyfat = rs1.getFloat(14);
    		 		rightarm_muscle = rs1.getInt(15);
    		 		rightarm_muscle = rs1.getInt(16);
    		 		leftleg_muscle = rs1.getInt(17);
    		 		rightleg_muscle = rs1.getInt(18);
    		 		center_muscle = rs1.getInt(19);
    		 		leftarm_fat = rs1.getInt(20);
    		 		leftleg_fat = rs1.getInt(21);
    		 		rightarm_fat = rs1.getInt(22);
    		 		rightleg_fat = rs1.getInt(23);
    		 		center_fat = rs1.getInt(24);
    		 	}

    		 

    		 }catch(Exception e){
    		 	e.printStackTrace();
    		 }finally{
    			if(rs1 !=null)
    					try{rs1.close();}catch(SQLException sqle){}
    		 	if(pstmt1 != null)
    		 		try{pstmt1.close();}catch(SQLException sqle){}
    		 	if(conn1 != null)
    		 		try{conn1.close();}catch(SQLException sqle){}

    		 }

      out.write("\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>아이디<br>");
      out.print(name );
      out.write("</td>\r\n");
      out.write("                    \t\t<td>신장<br>");
      out.print(height );
      out.write("cm</td>\r\n");
      out.write("                    \t\t<td>연령<br>");
      out.print(age );
      out.write("</td>\r\n");
      out.write("                    \t\t<td>성별<br>");
if(sex == 1){
      out.write('남');
      out.write('자');
}else{
      out.write('여');
      out.write('자');
} 
      out.write("</td>\r\n");
      out.write("                    \t\t<td>검사일시<br>");
      out.print(check_date );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                     <h4>체성분분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>우리 몸을 이루고 있는 물</td><td>체수분(L)</td><td>");
      out.print(totalbodywater );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>근육을 만들어 주는</td><td>단백질(kg)</td><td>");
      out.print(protein );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>뼈를 단단하게 해주는</td><td>무기질(kg)</td><td>");
      out.print(mineral );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>남은 에너지를 저장해 놓은</td><td>체지방량(kg)</td><td>");
      out.print(bodyfat );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체수분, 단백질, 무기질, 체지방을 모두 합하면</td><td>체중(kg)</td><td>");
      out.print(weight );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                    <h4>골격근 지방 분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td></td><td>측정치</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체중(kg)</td><td>");
      out.print(weight );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>골격근량(kg)</td><td>");
      out.print(skeletal_muscle_mass );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체지방량(kg)</td><td>");
      out.print(bodyfat );
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                    <h4>비만분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td></td><td>측정치</td><td>비고</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>BMI(kg/㎡)</td><td>");
      out.print(bmi );
      out.write("</td>\r\n");
      out.write("                    \t\t<td>\r\n");
      out.write("                    \t\t\t");

                    				if(bmi >= 30)
                    				{
                    					
      out.write("고도비만");

                    				}
                    				else if(bmi >= 25)
                    				{
                    					
      out.write('비');
      out.write('만');

                    				}
                    				else if(bmi >= 23)
                    				{
                    					
      out.write('과');
      out.write('체');
      out.write('중');

                    				}
                    				else if(bmi >= 18.5)
                    				{
                    					
      out.write('평');
      out.write('균');

                    				}
                    				else
                    				{
                    					
      out.write("평균이하");

                    				} 
                    			
      out.write("\r\n");
      out.write("                    \t\t</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>체지방률(%)</td><td>");
      out.print(percentbodyfat );
      out.write("</td><td>");
if(percentbodyfat >= 20){
      out.write("평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i>");
}else if(percentbodyfat >= 10){
      out.write('평');
      out.write('균');
}else{
      out.write("평균이하<i class=\"zmdi zmdi-long-arrow-down\">");
} 
      out.write("</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table><hr><br>\r\n");
      out.write("                    <h4>부위별 분석</h4>\r\n");
      out.write("                    <table class=\"table table-hover table-striped\">\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">부위별근육분석</td>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">부위별체지방분석</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>왼팔근육(");
if(rightarm_muscle == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(rightarm_muscle == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른팔근육(");
if(rightarm_muscle == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(rightarm_muscle == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td>왼팔지방(");
if(leftarm_fat == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(leftarm_fat == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른팔지방(");
if(rightarm_fat == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(rightarm_fat == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">복부근육(");
if(center_muscle == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(center_muscle == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td colspan=\"2\" align=\"center\">복부지방(");
if(center_fat == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(center_fat == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                    \t\t<td>왼다리근육(");
if(leftleg_muscle == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(leftleg_muscle == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른다리근육(");
if(rightleg_muscle == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(rightleg_muscle == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td>왼다리지방(");
if(leftarm_fat == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(leftarm_fat == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t\t<td align=\"right\">오른다리지방(");
if(rightleg_fat == 0) {
      out.write(" 평균이하<i class=\"zmdi zmdi-long-arrow-down\"> ");
}else if(rightleg_fat == 1) { 
      out.write(' ');
      out.write('평');
      out.write('균');
 } else {
      out.write(" 평균이상<i class=\"zmdi zmdi-long-arrow-up\"></i> ");
 } 
      out.write(")</td>\r\n");
      out.write("                    \t</tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                     <div align=\"center\">\r\n");
      out.write("                    \t<button type=\"button\" class=\"btn btn-light btn-block\" style=\"width:20%; background-color: #01b1d7; fon\" onclick=\"location.href='/health/health_rec_list.jsp?name=");
      out.print(name);
      out.write("&check_date=");
      out.print(check_date);
      out.write("' \"><font color=\"white\">운동/식단 추천받기</font></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("  \t</div>\r\n");
      out.write("    \t   ");

    	    		 
      }

      out.write("\r\n");
      out.write("  \r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("              <h3>EasyET</h3>\r\n");
      out.write("              <p>\r\n");
      out.write("                                    경기도 부천시 경인로 590 <br>\r\n");
      out.write("                <strong>Phone:</strong> +82 02-2610-0600<br>\r\n");
      out.write("                <strong>Email:</strong> chk4814@naver.com<br>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6 footer-links\">\r\n");
      out.write("            <h4>사이트맵</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("              \t<a href=\"/index.jsp\">Home</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/health/health.jsp\">건강정보</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/board/board_list.jsp\">소통게시판</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp&nbsp\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        &copy; Copyright <strong><span>MyBiz</span></strong>. All Rights Reserved\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"credits\">\r\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\r\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\r\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
