/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-01 01:15:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.io.*;
import java.sql.Timestamp;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class notice_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Timestamp");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 여기 작성 -->\n");

	request.setCharacterEncoding("UTF-8");

	String login = (String)session.getAttribute("Login");
	String userid = (String)session.getAttribute("UserID");

      out.write('\n');

		 
		final int ROWSIZE = 10;
		final int BLOCK = 8;
			
		int pg = 1;
		
		if(request.getParameter("pg")!=null) {
			pg = Integer.parseInt(request.getParameter("pg"));
		}
		
		int start = (pg*ROWSIZE) - (ROWSIZE-1);
		int end = (pg*ROWSIZE);
		
		int allPage = 0;
		
		int startPage = ((pg-1)/BLOCK*BLOCK)+1;
		int endPage = ((pg-1)/BLOCK*BLOCK)+BLOCK;

      out.write("\n");
      out.write("\t<!-- 작성 끝 -->\n");
      out.write("    <!DOCTYPE html>\n");
      out.write("<html lang=\"utf-8\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\n");
      out.write("<!-- 이미지 미리보기 할 때 필요한 script -->\n");
      out.write("  <title>Welcome EasyET</title>\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\n");
      out.write("  <meta content=\"\" name=\"keywords\">\n");
      out.write("\n");
      out.write("  <!-- Favicons -->\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("  <!-- Google Fonts -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Vendor CSS Files -->\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Template Main CSS File -->\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- =======================================================\n");
      out.write("  * Template Name: MyBiz - v2.1.0\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\n");
      out.write("  * Author: BootstrapMade.com\n");
      out.write("  * License: https://bootstrapmade.com/license/\n");
      out.write("  ======================================================== -->\n");
      out.write("<style>\n");
      out.write(".contact  {\n");
      out.write("  width: 100%;\n");
      out.write("  box-shadow: 0 0 24px 0 rgba(0, 0, 0, 0.12);\n");
      out.write("  padding: 30px;\n");
      out.write("  background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .form-group {\n");
      out.write("  padding-bottom: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .validate {\n");
      out.write("  display: none;\n");
      out.write("  color: red;\n");
      out.write("  margin: 0 0 15px 0;\n");
      out.write("  font-weight: 400;\n");
      out.write("  font-size: 13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .error-message {\n");
      out.write("  display: none;\n");
      out.write("  color: #fff;\n");
      out.write("  background: #ed3c0d;\n");
      out.write("  text-align: left;\n");
      out.write("  padding: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .error-message br + br {\n");
      out.write("  margin-top: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .sent-message {\n");
      out.write("  display: none;\n");
      out.write("  color: #fff;\n");
      out.write("  background: #18d26e;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 15px;\n");
      out.write("  font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .loading {\n");
      out.write("  display: none;\n");
      out.write("  background: #fff;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .loading:before {\n");
      out.write("  content: \"\";\n");
      out.write("  display: inline-block;\n");
      out.write("  border-radius: 50%;\n");
      out.write("  width: 24px;\n");
      out.write("  height: 24px;\n");
      out.write("  margin: 0 10px -6px 0;\n");
      out.write("  border: 3px solid #18d26e;\n");
      out.write("  border-top-color: #eee;\n");
      out.write("  -webkit-animation: animate-loading 1s linear infinite;\n");
      out.write("  animation: animate-loading 1s linear infinite;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact  input, .contact textarea {\n");
      out.write("  border-radius: 0;\n");
      out.write("  box-shadow: none;\n");
      out.write("  font-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact input {\n");
      out.write("  height: 44px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact textarea {\n");
      out.write("  padding: 10px 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact button[type=\"submit\"] {\n");
      out.write("  background: #01b1d7;\n");
      out.write("  border: 0;\n");
      out.write("  padding: 10px 24px;\n");
      out.write("  color: #fff;\n");
      out.write("  transition: 0.4s;\n");
      out.write("  border-radius: 4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact  button[type=\"submit\"]:hover {\n");
      out.write("  background: #0dd3fe;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact  button{\n");
      out.write("  background: #01b1d7;\n");
      out.write("  border: 0;\n");
      out.write("  padding: 10px 24px;\n");
      out.write("  color: #fff;\n");
      out.write("  transition: 0.4s;\n");
      out.write("  border-radius: 4px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- ======= Top Bar ======= -->\n");
      out.write("  <section id=\"topbar\" class=\"d-none d-lg-block\">\n");
      out.write("    <div class=\"container d-flex\">\n");
      out.write("      <div class=\"contact-info mr-auto\">\n");
      out.write("        <i class=\"icofont-envelope\"></i><a href=\"mailto:chk4814@naver.com \">chk4814@naver.com </a>\n");
      out.write("        <i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <div>\n");
      out.write("      \t ");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\n");
      out.write("    \t  \t<a href=\"/login/login_form.jsp\" >LOGIN</a> \n");
      out.write("      \t \t<a href=\"/join/join_form.jsp\" >JOIN</a>\n");
      out.write("    \t  ");

      	}
      	else
      	{
    	  
      out.write("\n");
      out.write("    \t  \t<a href=\"/login/logout_action.jsp\" >LOGOUT</a> \n");
      out.write("      \t \t<a href=\"/mypage/mypage.jsp\" >MYPAGE</a>\n");
      out.write("    \t  ");

      	}
      
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- ======= Header ======= -->\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\n");
      out.write("    <div class=\"container d-flex align-items-center\">\n");
      out.write("\n");
      out.write("      <div class=\"logo mr-auto\">\n");
      out.write("        <h1 class=\"text-light\"><a href=\"/index.jsp\">Easy<span>ET</span></a></h1>\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block\">\n");
      out.write("        <ul>\n");
      out.write("          <li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\n");
      out.write("          <li><a href=\"/health/health.jsp\">건강정보</a></li>\n");
      out.write("          <li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\n");
      out.write("          <li class=\"drop-down\"><a href=\"\">Board</a>\n");
      out.write("          \t<ul>\n");
      out.write("          \t\t<li><a href=\"/board/board_list.jsp\">게시판</a></li>\n");
      out.write("          \t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\n");
      out.write("          \t</ul>\n");
      out.write("        </ul>\n");
      out.write("      </nav><!-- .nav-menu -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </header><!-- End Header -->\n");
      out.write("\n");
      out.write("  <main id=\"main\">\n");
      out.write("  \t<!-- 여기다 코딩 -->\n");
      out.write("\t<div class=\"container contact\">\n");
      out.write("\t\t\t<div class=\"row content\" >\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\" style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t<h1 align=\"center\">공지사항</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t");

			if(session.getAttribute("ss") != null){
				if(session.getAttribute("ss").equals("admin@naver.com"))
				{
			
      out.write("\n");
      out.write("\t    \t\t\t<div style=\"align:right;\">\n");
      out.write("\t\t\t\t\t<a href=\"notice_insert_form.jsp?pg=");
      out.print(pg);
      out.write("\"><button class=\"btn btn-default\">글 작성하기</button></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t");

				}
			}
			
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<div class=\"row\"></div>\n");
      out.write("\t\t\t<div class=\"row content\">\n");
      out.write("\t\t\t\t<table class=\"table table-hover table-striped\">\n");
      out.write("\t\t\t\t\t<tr style=\"font-weight:bold; font-size:15px;text-align:center;border-top:2px solid #b0b0b0;border-bottom:2px solid #b0b0b0;height:40px;\">\n");
      out.write("\t\t\t\t\t\t<td style=\"width:7%\">No</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:30%\">제목</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:25%\">작성자</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:23%\">작성일</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:8%\">조회수</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t");

						PreparedStatement pstmt=null;
						ResultSet rs = null;
					
						String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
						String dbId="yhpj";
						String dbPass="Yuhan2020!";
						int total = 0;

						String Notice_Uid = null;
						String Notice_Title = null;
						String Notice_Name = null;
						//Timestamp Notice_Date = new Timestamp(System.currentTimeMillis());
						String Notice_Date = null;
						String Notice_Look_Cnt = null;
						
						try{
							Class.forName("com.mysql.jdbc.Driver"); 
							Connection conn = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
					
							String count = "select count(*) from notice";
							pstmt = conn.prepareStatement(count);
							rs= pstmt.executeQuery();
							
							if(rs.next())
							{
								total = rs.getInt(1);
							}
							
							allPage = (int)Math.ceil(total/(double)ROWSIZE);
							
							if(endPage > allPage) {
								endPage = allPage;
							}
							
							//String NoticeSQL="SELECT * FROM notice ORDER BY notice_uid DESC";
							String NoticeSQL="SELECT * FROM notice WHERE notice_uid >= "+ start +" AND notice_uid <= " +end + " ORDER BY notice_uid DESC";
							pstmt = conn.prepareStatement(NoticeSQL);
							rs = pstmt.executeQuery();
					
							while(rs.next())
							{	
								Notice_Uid = rs.getString(1);
								Notice_Title = rs.getString(3);
								Notice_Name = "관리자";
								Notice_Date = rs.getString(5); 
								Notice_Look_Cnt = rs.getString(6);
								
								Date date = new Date(); 
								SimpleDateFormat simpleDate = new SimpleDateFormat("yyyy-MM-dd"); 
								String year = (String)simpleDate.format(date); 
								String yea = Notice_Date.substring(0,10);
								
					
      out.write("\n");
      out.write("\t\t\t\t\t<tr style=\"text-align:center;\" class=\"content\">\n");
      out.write("\t\t\t\t\t\t<td style=\"width:7%\">");
      out.print( Notice_Uid );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:30%\">\n");
      out.write("\t\t\t\t\t\t<a href=\"notice_detail_form.jsp?noticeid=");
      out.print( Notice_Uid );
      out.write("&pg=");
      out.print(pg);
      out.write("\"> \n");
      out.write("\t\t\t\t\t\t\t");
      out.print( Notice_Title );
      out.write(" </a>");

											if(year.equals(yea)){
										
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;<img src='./NoticeIcon/Icon_New.png' width=\"10\" /> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}  
										
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:25%\">");
      out.print( Notice_Name );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:23%\">");
      out.print( yea );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t<td style=\"width:8%\">");
      out.print( Notice_Look_Cnt );
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("<hr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"7\" align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");

								if(pg>BLOCK) {
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice_list.jsp?pg=1\" class=\"btn btn-default\" style=\"background-color: gray;\">&laquo;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice_list.jsp?pg=");
      out.print(startPage-1);
      out.write("\" class=\"btn btn-default\" style=\"background-color: gray;\">&lt;</a>\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");

								for(int i=startPage; i<= endPage; i++){
									if(i==pg){
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice_list.jsp?pg=");
      out.print(i );
      out.write("\" class=\"btn btn-default\" style=\"background-color: gray;\"><font color=\"white\">");
      out.print(i );
      out.write("</font></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else{
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice_list.jsp?pg=");
      out.print(i );
      out.write("\" class=\"btn btn-default\" style=\"background-color: gray;\"><font color=\"white\">");
      out.print(i );
      out.write("</font></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								if(endPage<allPage){
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice_list.jsp?pg=");
      out.print(endPage+1);
      out.write("\">&gt;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"notice_list.jsp?pg=");
      out.print(allPage);
      out.write("\">&raquo;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\"></div>\t\n");
      out.write("    \t</div>\n");
      out.write("\t\t");

			conn.close();
			
			}catch(ClassNotFoundException e){
				out.println("Where is your mysql jdbc driver?");
				e.printStackTrace();
				//return;
			}
		
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("  </main>\n");
      out.write("<!-- End #main -->\n");
      out.write("\n");
      out.write("  <!-- ======= Footer ======= -->\n");
      out.write("  <footer id=\"footer\">\n");
      out.write("    <div class=\"footer-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-6 col-md-6\">\n");
      out.write("            <div class=\"footer-info\">\n");
      out.write("              <h3>EasyET</h3>\n");
      out.write("              <p>\n");
      out.write("                                    경기도 부천시 경인로 590 <br>\n");
      out.write("                <strong>Phone:</strong> +82 02-2610-0600<br>\n");
      out.write("                <strong>Email:</strong> chk4814@naver.com<br>\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-6 col-md-6 footer-links\">\n");
      out.write("            <h4>사이트맵</h4>\n");
      out.write("            <ul>\n");
      out.write("              <li>\n");
      out.write("              \t<a href=\"/index.jsp\">Home</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/health/health.jsp\">건강정보</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/board/board_list.jsp\">게시판</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp&nbsp\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"copyright\">\n");
      out.write("        &copy; Copyright <strong><span>MyBiz</span></strong>. All Rights Reserved\n");
      out.write("      </div>\n");
      out.write("      <div class=\"credits\">\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer><!-- End Footer -->\n");
      out.write("\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\n");
      out.write("\n");
      out.write("  <!-- Vendor JS Files -->\n");
      out.write("  <script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Template Main JS File -->\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
