/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-03 11:13:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Welcome EasyET</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: MyBiz - v2.1.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

int user_count = 0;
int health_count = 0;
int board_count = 0;

Connection conn = null;
PreparedStatement pstmt = null;
ResultSet rs = null;
String str = "";
try{
	 String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
	 String dbId = "yhpj";
	 String dbPass = "Yuhan2020!";
	
	Class.forName ("com.mysql.jdbc.Driver"); //driver load
	conn = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
	
	str = "select count(user_id) from user";
	pstmt = conn.prepareStatement(str);
	rs = pstmt.executeQuery();
	
	while(rs.next())
	{
		user_count = rs.getInt(1);
	}
	
	str = "select count(uid) from inbody";
	pstmt = conn.prepareStatement(str);
	rs = pstmt.executeQuery();
	
	while(rs.next())
	{
		health_count = rs.getInt(1);
	}
	
	str = "select count(board_uid) from board";
	pstmt = conn.prepareStatement(str);
	rs = pstmt.executeQuery();
	
	while(rs.next())
	{
		board_count = rs.getInt(1);
	}

}catch(Exception e){
	e.printStackTrace();
}finally{
	if(rs !=null)
			try{rs.close();}catch(SQLException sqle){}
	if(pstmt != null)
		try{pstmt.close();}catch(SQLException sqle){}
	if(conn != null)
		try{conn.close();}catch(SQLException sqle){}

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Top Bar ======= -->\r\n");
      out.write("  <section id=\"topbar\" class=\"d-none d-lg-block\">\r\n");
      out.write("    <div class=\"container d-flex\">\r\n");
      out.write("      <div class=\"contact-info mr-auto\">\r\n");
      out.write("        <i class=\"icofont-envelope\"></i><a href=\"mailto:contact@example.com\">chk4814@naver.com</a>\r\n");
      out.write("        <i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("      ");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/login_form.jsp\" >LOGIN</a> \r\n");
      out.write("      \t \t<a href=\"/join/join_form.jsp\" >JOIN</a>\r\n");
      out.write("    \t  ");

      	}
      	else
      	{
    	  
      out.write("\r\n");
      out.write("    \t  \t<a href=\"/login/logout_action.jsp\" >LOGOUT</a> \r\n");
      out.write("      \t \t<a href=\"/mypage/mypage.jsp\" >MYPAGE</a>\r\n");
      out.write("    \t  ");

      	}
      
      out.write(" \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("    <div class=\"container d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"logo mr-auto\">\r\n");
      out.write("        <h1 class=\"text-light\"><a href=\"/index.jsp\">Easy<span>ET</span></a></h1>\r\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"/health/health.jsp\">건강정보</a></li>\r\n");
      out.write("          <li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\r\n");
      out.write("          <li class=\"drop-down\"><a href=\"\">Board</a>\r\n");
      out.write("          \t<ul>\r\n");
      out.write("          \t\t<li><a href=\"/board/board_list.jsp\">소통 게시판</a></li>\r\n");
      out.write("          \t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\r\n");
      out.write("          \t</ul>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav><!-- .nav-menu -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Hero Section ======= -->\r\n");
      out.write("  <section id=\"hero\">\r\n");
      out.write("    <div class=\"hero-container\">\r\n");
      out.write("      <div id=\"heroCarousel\" class=\"carousel slide carousel-fade\" data-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("        <ol class=\"carousel-indicators\" id=\"hero-carousel-indicators\"></ol>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("          <!-- Slide 1 -->\r\n");
      out.write("          <div class=\"carousel-item active\" style=\"background-image: url(assets/img/slide/main1.jpg);\">\r\n");
      out.write("            <div class=\"carousel-container\">\r\n");
      out.write("              <div class=\"carousel-content\">\r\n");
      out.write("                <h2 class=\"animate__animated animate__fadeInDown\">Welcome to <span>EasyET</span></h2>\r\n");
      out.write("                <p class=\"animate__animated animate__fadeInUp\">개인건강관리 솔루션 EasyET에 오신걸 환영합니다. EasyET는 개인별 맞춤 운동과 식단 추천을 통하여 바쁜 현대인들의 건강관리에 도움을 줍니다. </p>\r\n");
      out.write("                <a href=\"/login/login_form.jsp\" class=\"btn-get-started scrollto animate__animated animate__fadeInUp\">지금 시작해 보기</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Slide 2 -->\r\n");
      out.write("          <div class=\"carousel-item\" style=\"background-image: url(assets/img/slide/main2.jpg);\">\r\n");
      out.write("            <div class=\"carousel-container\">\r\n");
      out.write("              <div class=\"carousel-content\">\r\n");
      out.write("                <h2 class=\"animate__animated animate__fadeInDown\">운동 및 식단 추천</h2>\r\n");
      out.write("                <p class=\"animate__animated animate__fadeInUp\">작성한 인바디를 통해 본인에게 맞는 운동과 식단을 추천해줍니다.</p>\r\n");
      out.write("                <a href=\"/health/health.jsp\" class=\"btn-get-started scrollto animate__animated animate__fadeInUp\">인바디 작성하러 가기</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- Slide 3 -->\r\n");
      out.write("          <div class=\"carousel-item\" style=\"background-image: url(assets/img/slide/award.jpg);\">\r\n");
      out.write("            <div class=\"carousel-container\">\r\n");
      out.write("              <div class=\"carousel-content\">\r\n");
      out.write("                <h2 class=\"animate__animated animate__fadeInDown\">명예의 전당</h2>\r\n");
      out.write("                <p class=\"animate__animated animate__adeInUp\">한달마다 업데이트되는 명예의 전당을 확인해보세요! </p>\r\n");
      out.write("                <a href=\"/honor/honor.jsp\" class=\"btn-get-started scrollto animate__animated animate__fadeInUp\">명예의 전당 보기</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#heroCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon ri-arrow-left-line\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#heroCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon ri-arrow-right-line\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section><!-- End Hero -->\r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= About Section ======= -->\r\n");
      out.write("    <section id=\"about\" class=\"about\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row content\">\r\n");
      out.write("          <div class=\"col-lg-6\">\r\n");
      out.write("            <h2>개인건강관리 솔루션 EasyET</h2>\r\n");
      out.write("            <h3>EasyET는 개인별 맞춤 운동과 식단 추천을 통하여 바쁜 현대인들의 건강관리에 도움을 줍니다. </h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6 pt-4 pt-lg-0\">\r\n");
      out.write("            <p>\r\n");
      out.write("             \t사람들은 건강하고 오래 사는 것(건강수명)을 추구하고 있습니다.치료방향 또한 병이 발병하기 전에 미리 관리하는 시대로 가고 있어 건강관리의 중요성이 더욱더 부각됩니다.  \r\n");
      out.write("             \t또한 전세계적으로 유행하고 있는 코로나 때문에 사람들이 헬스장 같은 운동시설을 이용하지 못해 건강관리의 어려움을 겪고 있습니다.따라서 집에 있는 시간이 길어져 집에서 스스로 건강관리를 해야 하는 필요성이 대두되고 있습니다.\r\n");
      out.write("            </p>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><i class=\"ri-check-double-line\"></i> 신자유주의의 강화로 인한 노동 시간과 노동 강도의 강화</li>\r\n");
      out.write("              <li><i class=\"ri-check-double-line\"></i> 직업의 불안정성과 다양한 스트레스원의 증가</li>\r\n");
      out.write("              <li><i class=\"ri-check-double-line\"></i> 운동 부족, 흡연과 음주, 지방과 육류 과다 섭취</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p class=\"font-italic\">\r\n");
      out.write("             \t 건강관리에 미숙한 사람들은 혼자서 자신의 건강을 관리하기에는 무리가 있습니다. \r\n");
      out.write("             \t 따라서 이 웹 사이트는 사용자의 건강정보를 바탕으로 알맞은 운동방법 및 식단을 제공하여 사용자 스스로 건강관리를 할 수 있도록 도와줍니다.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End About Section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= About List Section ======= -->\r\n");
      out.write("    <section id=\"about-list\" class=\"about-list\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-6 order-2 order-lg-1\">\r\n");
      out.write("            <div class=\"icon-box mt-5 mt-lg-0\">\r\n");
      out.write("              <i class=\"bx bx-receipt\"></i>\r\n");
      out.write("              <h4>개인별 맞춤 운동/식단 추천</h4>\r\n");
      out.write("              <p>사용자의 건강정보를 입력받아 알맞은 운동과 식단을 추천해줍니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"icon-box mt-5\">\r\n");
      out.write("              <i class=\"icofont-award\"></i>\r\n");
      out.write("              <h4>명예의 전당</h4>\r\n");
      out.write("              <p>이 달의 다이어트 왕을 선정하여 혼자 운동하는 사람들에게 동기부여를 해줍니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"icon-box mt-5\">\r\n");
      out.write("              <i class=\"bx bx-images\"></i>\r\n");
      out.write("              <h4>게시판</h4>\r\n");
      out.write("              <p>사용자들간의 소통을 원할하게 합니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"icon-box mt-5\">\r\n");
      out.write("              <i class=\"bx bx-shield\"></i>\r\n");
      out.write("              <h4>개인정보 관리</h4>\r\n");
      out.write("              <p>EasyET는 필요한 정보만을 수집하며 탈퇴 시 모든 정보를 삭제합니다. </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"image col-lg-6 order-1 order-lg-2\" style='background-image: url(\"assets/img/about-list-img.jpg\");'></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End About List Section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= Counts Section ======= -->\r\n");
      out.write("    <section id=\"counts\" class=\"counts\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text-center title\">\r\n");
      out.write("          <h3>EasyET는 당신의 건강을 응원합니다.</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row counters\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-6 text-center\">\r\n");
      out.write("            <span data-toggle=\"counter-up\">");
      out.print(user_count );
      out.write("</span>\r\n");
      out.write("            <p>가입한 회원</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-6 text-center\">\r\n");
      out.write("            <span data-toggle=\"counter-up\">");
      out.print(health_count );
      out.write("</span>\r\n");
      out.write("            <p>입력된 건강정보</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-6 text-center\">\r\n");
      out.write("            <span data-toggle=\"counter-up\">");
      out.print(board_count );
      out.write("</span>\r\n");
      out.write("            <p>작성된 게시글</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Counts Section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= Team Section ======= -->\r\n");
      out.write("    <section id=\"team\" class=\"team\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("          <h2>공지사항</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \r\n");
      out.write("        \t<table class=\"table table-hover table-striped\">\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t\t<td>제목</td><td align=\"right\">작성일</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t\t");

        	Connection conn1 = null;
        	PreparedStatement pstmt1 = null;
        	ResultSet rs1 = null;
        	String strfirst = "";
        	String cuttime = null;
        	
        	try{
        		 String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
        		 String dbId = "yhpj";
        		 String dbPass = "Yuhan2020!";
        		
        		Class.forName ("com.mysql.jdbc.Driver"); //driver load
        		conn1 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);

        		strfirst = "SELECT notice_uid, notice_title, notice_date from notice order by notice_date desc limit 5";
        		pstmt1 = conn1.prepareStatement(strfirst);
        		rs1 = pstmt1.executeQuery();
        		
        		while(rs1.next())
        		{
        			cuttime = rs1.getString(3).substring(0, 9);
        			
      out.write("  \r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t\t<tr>\r\n");
      out.write("        \t\t\t\t\t\t<td><a href=\"/notice/notice_detail_form.jsp?noticeid=");
      out.print(rs1.getInt(1));
      out.write('"');
      out.write('>');
      out.print(rs1.getString(2) );
      out.write("</a></td><td align=\"right\">");
      out.print(rs1.getString(3).substring(0, 10) );
      out.write("</td>\r\n");
      out.write("        \t\t\t\t\t</tr>\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t");

        		}

        	}catch(Exception e){
        		e.printStackTrace();
        	}finally{
        		if(rs1 !=null)
        				try{rs1.close();}catch(SQLException sqle){}
        		if(pstmt1 != null)
        			try{pstmt1.close();}catch(SQLException sqle){}
        		if(conn1 != null)
        			try{conn1.close();}catch(SQLException sqle){}

        	}
        	
      out.write("\r\n");
      out.write("        \t</table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Team Section -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("              <h3>EasyET</h3>\r\n");
      out.write("              <p>\r\n");
      out.write("                                    경기도 부천시 경인로 590 <br>\r\n");
      out.write("                <strong>Phone:</strong> +82 02-2610-0600<br>\r\n");
      out.write("                <strong>Email:</strong> chk4814@naver.com<br>\r\n");
      out.write("              </p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-6 col-md-6 footer-links\">\r\n");
      out.write("            <h4>사이트맵</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>\r\n");
      out.write("              \t<a href=\"/index.jsp\">Home</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/health/health.jsp\">건강정보</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/board/board_list.jsp\">소통게시판</a>&nbsp&nbsp\r\n");
      out.write("              \t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp&nbsp\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"copyright\">\r\n");
      out.write("        &copy; Copyright <strong><span>MyBiz</span></strong>. All Rights Reserved\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"credits\">\r\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\r\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\r\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
