/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-04 08:43:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.util.*;
import java.io.*;
import com.oreilly.servlet.MultipartRequest;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;

public final class board_005fdetail_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


request.setCharacterEncoding("UTF-8"); 
//String ss = session.getAttribute("ss").toString();
String id = (String)session.getAttribute("ss");

int boardid = Integer.parseInt(request.getParameter("boardid")); //BoardList에서 board_uid 받아오기

int pg = 1;

if(request.getParameter("pg")!=null) {
	pg = 1; 
	pg = Integer.parseInt(request.getParameter("pg"));
	}


Connection conn = null;
PreparedStatement pstmt = null;
ResultSet rs = null;
ResultSet rs1 = null;
ResultSet rs2 = null;

String driverName = "com.mysql.jdbc.Driver";
String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj?useSSL=false&;useUnicode=true&characterEncoding=utf8";
String dbId = "yhpj"; //dbid설정
String dbPass = "Yuhan2020!"; //db비밀번호 설정

String compareid = "qwe";
String comparereplyid = "qwe";

      out.write('\n');
      out.write('\n');

    		 Connection conn7 = null;
    		 PreparedStatement pstmt7 = null;
    		 ResultSet rs7 = null;
    		 String strfirst = "";
    		 try{
    			  jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
    			  dbId = "yhpj";
    			  dbPass = "Yuhan2020!";
    		 	
    		 	Class.forName ("com.mysql.jdbc.Driver"); //driver load
    		 	conn7 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
    		 	
				strfirst = "select name from board_good where uid=?";
    		 	pstmt7 = conn7.prepareStatement(strfirst);
    		 	pstmt7.setInt(1,boardid);
    		 	rs7 = pstmt7.executeQuery();
    		 	
    		 	if(rs7.next())
    		 	{
    		 		compareid = rs7.getString(1);
    		 	}
    		 	
    		 	


    		 }catch(Exception e){
    		 	e.printStackTrace();
    		 }finally{
    			if(rs7 !=null)
    					try{rs7.close();}catch(SQLException sqle){}
    		 	if(pstmt7 != null)
    		 		try{pstmt7.close();}catch(SQLException sqle){}
    		 	if(conn7 != null)
    		 		try{conn7.close();}catch(SQLException sqle){}

    		 }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"utf-8\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("\n");
      out.write("<title>Welcome EasyET</title>\n");
      out.write("<!-- 작성 시작 -->\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-2.1.0.min.js\"></script>\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction check() {\n");
      out.write("\t\tif (BoardReplyForm.BoardReply_Content.value == \"\") {\n");
      out.write("\t\t\talert('댓글 내용을 입력하세요');\n");
      out.write("\t\t\tBoardReplyForm.BoardReply_Content.focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction goBack() {\n");
      out.write("\t\t/*  window.history.back(); */\n");
      out.write("\t\tlocation.href = \"board_list.jsp?pg=\" + pg;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\tinput.goodimg-button{\n");
      out.write("\t\tbackground: url('./BoardIcon/Icon_RGood.png') no-repeat;\n");
      out.write("\t\tbackground-size: 99%;\n");
      out.write("\t\tborder : none;\n");
      out.write("\t\twidth: 25px;\n");
      out.write("\t\theight: 25px;\n");
      out.write("\t\tcursor : pointer;\n");
      out.write("\t\tmargin-left: 100px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tinput.goodimg-buttonblue{\n");
      out.write("\t\tbackground: url('./BoardIcon/icon_bluegood.png') no-repeat;\n");
      out.write("\t\tbackground-size: 99%;\n");
      out.write("\t\tborder : none;\n");
      out.write("\t\twidth: 25px;\n");
      out.write("\t\theight: 25px;\n");
      out.write("\t\tcursor : pointer;\n");
      out.write("\t\tmargin-left: 100px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tinput.goodimg-button2{\n");
      out.write("\t\tbackground: url('./BoardIcon/Icon_RGood.png') no-repeat;\n");
      out.write("\t\tbackground-size: 99%;\n");
      out.write("\t\tborder : none;\n");
      out.write("\t\twidth: 35px;\n");
      out.write("\t\theight: 35px;\n");
      out.write("\t\tcursor : pointer;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tinput.goodimg-button2blue{\n");
      out.write("\t\tbackground: url('./BoardIcon/icon_bluegood.png') no-repeat;\n");
      out.write("\t\tbackground-size: 99%;\n");
      out.write("\t\tborder : none;\n");
      out.write("\t\twidth: 35px;\n");
      out.write("\t\theight: 35px;\n");
      out.write("\t\tcursor : pointer;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("<!-- 작성 끝 -->\n");
      out.write("<meta content=\"\" name=\"descriptison\">\n");
      out.write("<meta content=\"\" name=\"keywords\">\n");
      out.write("\n");
      out.write("<!-- Favicons -->\n");
      out.write("<link href=\"/assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("<link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("<!-- Google Fonts -->\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Vendor CSS Files -->\n");
      out.write("<link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/boxicons/css/boxicons.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Template Main CSS File -->\n");
      out.write("<link href=\"/assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- =======================================================\n");
      out.write("  * Template Name: MyBiz - v2.1.0\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\n");
      out.write("  * Author: BootstrapMade.com\n");
      out.write("  * License: https://bootstrapmade.com/license/\n");
      out.write("  ======================================================== -->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- ======= Top Bar ======= -->\n");
      out.write("\t<section id=\"topbar\" class=\"d-none d-lg-block\">\n");
      out.write("\t\t<div class=\"container d-flex\">\n");
      out.write("\t\t\t<div class=\"contact-info mr-auto\">\n");
      out.write("\t\t\t\t<i class=\"icofont-envelope\"></i><a href=\"mailto:chk4814@naver.com\">chk4814@naver.com</a>\n");
      out.write("\t\t\t\t<i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t");

					if (session.getAttribute("ss") == null) {
				
      out.write("\n");
      out.write("\t\t\t\t<a href=\"/login/login_form.jsp\">LOGIN</a> <a\n");
      out.write("\t\t\t\t\thref=\"/join/join_form.jsp\">JOIN</a>\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\n");
      out.write("\t\t\t\t<a href=\"/login/logout_action.jsp\">LOGOUT</a> <a\n");
      out.write("\t\t\t\t\thref=\"/mypage/mypage.jsp\">MYPAGE</a>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<!-- ======= Header ======= -->\n");
      out.write("\t<header id=\"header\" class=\"d-flex align-items-center\">\n");
      out.write("\t\t<div class=\"container d-flex align-items-center\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"logo mr-auto\">\n");
      out.write("\t\t\t\t<h1 class=\"text-light\">\n");
      out.write("\t\t\t\t\t<a href=\"/index.jsp\">Easy<span>ET</span></a>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t\t<!-- Uncomment below if you prefer to use an image logo -->\n");
      out.write("\t\t\t\t<!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<nav class=\"nav-menu d-none d-lg-block\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/health/health.jsp\">건강정보</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"drop-down\"><a href=\"\">Board</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/board/board_list.jsp\">소통게시판</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<!-- .nav-menu -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- End Header -->\n");
      out.write("\n");
      out.write("\t<main id=\"main\">\n");
      out.write("\t\t<!-- 여기다 코딩 -->\n");
      out.write("\n");
      out.write("\t\t<div class=\"container contact\">\n");
      out.write("\t\t\t");

				try {
				//드라이버 로딩
				Class.forName("com.mysql.jdbc.Driver"); //Driver로 connection객체와 연결
				// connection 객체 세팅
				conn = DriverManager.getConnection(jdbcUrl, dbId, dbPass); //위에서 로딩한 드라이버를 가지고 connection객체에 연결

				SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				Calendar cal = Calendar.getInstance();
				
				String BoardReplyLookCntUpdateSQL = "UPDATE board SET board_look_cnt = board_look_cnt+"
												+	1
												+	" WHERE board_uid ="
												+	boardid;
		
				pstmt= conn.prepareStatement(BoardReplyLookCntUpdateSQL);
				pstmt.executeUpdate();
				pstmt.close();
				
				String BoardSQL = "SELECT * FROM board WHERE board_uid= ? ";
				pstmt = conn.prepareStatement(BoardSQL);
				pstmt.setInt(1, boardid);
				rs = pstmt.executeQuery();

				while (rs.next()) {
					String Board_Title = rs.getString("board_title");
					String Board_Writer = rs.getString("board_writer");
					String Board_Date = rs.getString("board_date");
					String Board_Content = rs.getString("board_content");
			
      out.write("\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\">\n");
      out.write("\t\t\t\t\t<h1 class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t[ ");
      out.print(Board_Title);
      out.write(" ]\n");
      out.write("\t\t\t\t\t</h1>\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<img src='./BoardIcon/Icon_Prof.png' \n");
      out.write("\t\t\t\t\t\tstyle=\"width:7%; margin-right: 10px; float: left;\">\n");
      out.write("\t\t\t\t\t\t<font size=\"5\">");
      out.print(Board_Writer);
      out.write("</font>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");

							
								try{
									Class.forName("com.mysql.jdbc.Driver"); 
									Connection conn2 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
							
									String sql = "SELECT NAME name1, MAX(weight) maxwei, MIN(weight) minwei FROM inbody HAVING MAX(maxwei-minwei)";
									pstmt = conn2.prepareStatement(sql);
									
									rs1= pstmt.executeQuery();
									
									while(rs1.next())
									{	
										String name1 = rs1.getString("name1");
										
										String sql2 = "SELECT name, Max(skeletal_muscle_mass), Min(skeletal_muscle_mass) FROM inbody group by name order by Max(skeletal_muscle_mass)-Min(skeletal_muscle_mass) DESC LIMIT 1"; 
										pstmt = conn2.prepareStatement(sql2);
										
										rs2= pstmt.executeQuery();
										
										while(rs2.next())
										{	
											String name2 = rs2.getString("name");
													
								if(name1.equals(Board_Writer) || name2.equals(Board_Writer)) //여기 수정하기
								{
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<img src='./BoardIcon/Icon_Queen.png' style=\"width:4%; margin-bottom:7px; float: left;\">\n");
      out.write("\t\t\t\t\t\t\t");

								} 
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");

										}	
									}
									rs2.close();
									rs1.close();
									conn2.close();
								
							
								}catch(ClassNotFoundException e){
									out.println("Where is your mysql jdbc driver?");
									e.printStackTrace();
									//return;
								}
				
							
      out.write("\t\n");
      out.write("\t\t\t\t\t\t<font size=\"3\" style=\"margin-left: 20px;\">&nbsp;&nbsp;");
      out.print(Board_Date);
      out.write("</font>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div style=\"float: right;\">\n");
      out.write("\t\t\t\t\t");

						if(compareid.equals(id) && compareid != null )
						{
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<input type=button class=\"goodimg-button2blue\"\n");
      out.write("\t\t\t\t\t\t\t\t\tOnClick=\"window.location='board_goodcnt_insert_action.jsp?boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("&what=delete'\">\n");
      out.write("\t\t\t\t\t\t\t");

						}
						else
						{
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<input type=button class=\"goodimg-button2\"\n");
      out.write("\t\t\t\t\t\t\t\tOnClick=\"window.location='board_goodcnt_insert_action.jsp?boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("&what=insert'\">\n");
      out.write("\t\t\t\t\t\t");

						}
					
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\">\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\"\n");
      out.write("\t\t\t\t\tstyle=\"margin-left: 20px; margin-right: 20px;\">\n");
      out.write("\t\t\t\t\t");
      out.print(Board_Content);
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\">\n");
      out.write("\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\">\n");
      out.write("\t\t\t\t\t<div class=\"panel-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a data-target=\"#collapseFour\" href=\"#collapseFour\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-toggle=\"gsdk-collapse\"> </a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									rs.close();
									pstmt.close();
									
									String BoardImgSQL = "SELECT * FROM boardimg WHERE board_uid=?";

									pstmt = conn.prepareStatement(BoardImgSQL);
									pstmt.setInt(1, boardid);
									
									rs = pstmt.executeQuery();
									while (rs.next()) {
										Integer BoardImg_Id = rs.getInt("boardimg_uid");
										String BoardImg_ChangeName = rs.getString("boardimg_changename");
										String BoardImg_SavePath = rs.getString("boardimg_savepath");
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <div id=\"circle\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<center> <img src=\"\\BoardSavePath\\");
      out.print( BoardImg_ChangeName );
      out.write("\" style=\"width:50%; height:auto;\"/> </center>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} //BoardImg 닫는부분
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"space-30\"></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\" style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t<button onclick=\"window.location='board_list.jsp?pg=");
      out.print(pg);
      out.write("'\"\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-info\">목록보기</button>\n");
      out.write("\t\t\t\t\t&nbsp;\n");
      out.write("\t\t\t\t\t");

						if (session.getAttribute("ss") != null)
						if (id.equals(Board_Writer)) {
					
      out.write("\n");
      out.write("\t\t\t\t\t<input type=button value=\"삭제\"\n");
      out.write("\t\t\t\t\t\tOnClick=\"window.location='board_delete_action.jsp?boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("'\"\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-danger\">\n");
      out.write("\t\t\t\t\t<input type=button value=\"수정\"\n");
      out.write("\t\t\t\t\t\tOnClick=\"window.location='board_modify_form.jsp?boardid=");
      out.print(boardid);
      out.write("&boardtitle=");
      out.print(Board_Title);
      out.write("&boardcontent=");
      out.print(Board_Content);
      out.write("&pg=");
      out.print(pg);
      out.write("'\"\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-danger\">\n");
      out.write("\t\t\t\t\t");

						}

					} //Board 닫는부분
					
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Board 게시물 내용 보여주는 곳 end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t");

					String sqlReplyCount = "SELECT COUNT(*) FROM boardreply WHERE board_uid = ?";
				pstmt = conn.prepareStatement(sqlReplyCount);
				pstmt.setInt(1, boardid);
				rs = pstmt.executeQuery();

				if (rs.next()) {
					Integer ReplyCount = rs.getInt(1);
				
      out.write("\n");
      out.write("\t\t\t\t<form name=\"BoardReplyForm\" method=\"post\" onsubmit=\"return check()\"\n");
      out.write("\t\t\t\t\taction=\"board_reply_insert_action.jsp?boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("&replycnt=");
      out.print(ReplyCount);
      out.write("\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-sm-12\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: Left; font-size: 25px;\">\n");
      out.write("\t\t\t\t\t\t\t댓글 &nbsp; <font color=\"#0080c0;\">");
      out.print(ReplyCount);
      out.write("</font>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t");

						if (session.getAttribute("ss") != null) {
					
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-top: 10px\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-sm-12\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: Left; size: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"BoardReply_Content\" id=\"BoardReply_Content\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"댓글 내용을 입력해 주세요\" cols=\"70\" rows=\"3\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"resize: none; letter-spacing: 1px;\" class=\"form-control\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-top: 10px\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-sm-12\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: right; size: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"댓글쓰기\" class=\"btn btn-info\" \n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"align: center; background-color: rgba(254, 210, 1, 0.98); color: white;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t");

					String BoardReplySQL = "SELECT * FROM boardreply WHERE board_uid = ? ORDER BY boardreply_uid DESC";

				pstmt = conn.prepareStatement(BoardReplySQL);
				pstmt.setInt(1, boardid);

				rs = pstmt.executeQuery();
				while (rs.next()) {
					String BoardReply_Uid = rs.getString("boardreply_uid");
					String BoardReply_Writer = rs.getString("boardreply_writer");
					String BoardReply_Content = rs.getString("boardreply_content");
					String BoardReply_Good_Cnt = rs.getString("boardreply_good_cnt");
					String BoardReply_Date = rs.getString("boardreply_date");
				
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");

    		 Connection conn8 = null;
    		 PreparedStatement pstmt8 = null;
    		 ResultSet rs8 = null;
    		 String strfirst2 = "";
    		 try{
    			  jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
    			  dbId = "yhpj";
    			  dbPass = "Yuhan2020!";
    		 	
    		 	Class.forName ("com.mysql.jdbc.Driver"); //driver load
    		 	conn8 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
    		 	
				strfirst2 = "select name from reply_good where board_uid=? and reply_uid=?";
    		 	pstmt8 = conn8.prepareStatement(strfirst2);
    		 	pstmt8.setInt(1,boardid);
    		 	pstmt8.setInt(2,Integer.parseInt(BoardReply_Uid));
    		 	rs8 = pstmt8.executeQuery();
    		 	
    		 	if(rs8.next())
    		 	{
    		 		comparereplyid = rs8.getString(1);
    		 	}
    		 	

    		 }catch(Exception e){
    		 	e.printStackTrace();
    		 }finally{
    			if(rs8 !=null)
    					try{rs8.close();}catch(SQLException sqle){}
    		 	if(pstmt8 != null)
    		 		try{pstmt8.close();}catch(SQLException sqle){}
    		 	if(conn8 != null)
    		 		try{conn8.close();}catch(SQLException sqle){}

    		 }

      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-sm-12\" style=\"align: center; size: 10px;\">\n");
      out.write("\t\t\t\t\t\t<table style=\"width:100%; align: center; font-size: 20px;\">\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<font size=\"5\">");
      out.print(BoardReply_Writer);
      out.write("</font> &nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t\t<font size=\"3\">");
      out.print(BoardReply_Date);
      out.write("</font>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (BoardReply_Writer.equals(id)) {
											
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"btn btn-danger\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"board_reply_delete_action.jsp?boardreplyid=");
      out.print(BoardReply_Uid);
      out.write("&boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("\"><font color=\"white\">삭제</font></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr style=\"margin-top: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"margin-left: 40px; width:70%;\">");
      out.print(BoardReply_Content);
      out.write(" </td>\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"align:right\">\n");
      out.write("\t\t\t\t\t\t\t\t");

									if(comparereplyid.equals(id) && comparereplyid != null)
									{
										
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=button class=\"goodimg-buttonblue\"\n");
      out.write("\t\t\t\t\t\t\t\t\tOnClick=\"window.location='board_reply_goodcnt_insert_action.jsp?boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("&boardreplyid=");
      out.print(BoardReply_Uid);
      out.write("&what=delete'\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

									}
									else
									{
										
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=button class=\"goodimg-button\"\n");
      out.write("\t\t\t\t\t\t\t\t\tOnClick=\"window.location='board_reply_goodcnt_insert_action.jsp?boardid=");
      out.print(boardid);
      out.write("&pg=");
      out.print(pg);
      out.write("&boardreplyid=");
      out.print(BoardReply_Uid);
      out.write("&what=insert'\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

									}
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"5\">");
      out.print(BoardReply_Good_Cnt );
      out.write("</font>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</table>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-sm-12\" style=\"align: center; size: 10px;\">\n");
      out.write("\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

					}

				rs.close();
				pstmt.close();
				conn.close();

				} catch (Exception e) {
				out.println("Where is your mysql jdbc driver?");
				out.println(e.getMessage());
				e.printStackTrace();
				}
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</main>\n");
      out.write("\t<!-- End #main -->\n");
      out.write("\n");
      out.write("\t<!-- ======= Footer ======= -->\n");
      out.write("\t<footer id=\"footer\">\n");
      out.write("\t\t<div class=\"footer-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-md-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-info\">\n");
      out.write("\t\t\t\t\t\t\t<h3>EasyET</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t경기도 부천시 경인로 590 <br> <strong>Phone:</strong> +82\n");
      out.write("\t\t\t\t\t\t\t\t02-2610-0600<br> <strong>Email:</strong> chk4814@naver.com<br>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-md-6 footer-links\">\n");
      out.write("\t\t\t\t\t\t<h4>사이트맵</h4>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"/index.jsp\">Home</a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t<a href=\"/health/health.jsp\">건강정보</a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t<a href=\"/board/board_list.jsp\">소통게시판</a>&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t\t&copy; Copyright <strong><span>MyBiz</span></strong>. All Rights\n");
      out.write("\t\t\t\tReserved\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"credits\">\n");
      out.write("\t\t\t\t<!-- All the links in the footer should remain intact. -->\n");
      out.write("\t\t\t\t<!-- You can delete the links only if you purchased the pro version. -->\n");
      out.write("\t\t\t\t<!-- Licensing information: https://bootstrapmade.com/license/ -->\n");
      out.write("\t\t\t\t<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\n");
      out.write("\t\t\t\tDesigned by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- End Footer -->\n");
      out.write("\n");
      out.write("\t<a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\n");
      out.write("\n");
      out.write("\t<!-- Vendor JS Files -->\n");
      out.write("\t<script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/php-email-form/validate.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Template Main JS File -->\n");
      out.write("\t<script src=\"/assets/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
