/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-03 07:28:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.io.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 여기 작성 -->\n");

		final int ROWSIZE = 10;
		final int BLOCK = 8;
			
		int pg = 1;
		
		if(request.getParameter("pg")!=null) {
			pg = Integer.parseInt(request.getParameter("pg"));
		}
		
		int start = (pg*ROWSIZE) - (ROWSIZE-1);
		int end = (pg*ROWSIZE);
		
		int allPage = 0;
		
		int startPage = ((pg-1)/BLOCK*BLOCK)+1;
		int endPage = ((pg-1)/BLOCK*BLOCK)+BLOCK;

      out.write("\n");
      out.write("<!-- 작성 끝 -->\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"utf-8\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\n");
      out.write("<!-- 이미지 미리보기 할 때 필요한 script -->\n");
      out.write("<title>Welcome EasyET</title>\n");
      out.write("<meta content=\"\" name=\"descriptison\">\n");
      out.write("<meta content=\"\" name=\"keywords\">\n");
      out.write("\n");
      out.write("<!-- Favicons -->\n");
      out.write("<link href=\"/assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("<link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("<!-- Google Fonts -->\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Vendor CSS Files -->\n");
      out.write("<link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/boxicons/css/boxicons.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Template Main CSS File -->\n");
      out.write("<link href=\"/assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- =======================================================\n");
      out.write("  * Template Name: MyBiz - v2.1.0\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\n");
      out.write("  * Author: BootstrapMade.com\n");
      out.write("  * License: https://bootstrapmade.com/license/\n");
      out.write("  ======================================================== -->\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".contact  {\n");
      out.write("  width: 100%;\n");
      out.write("  box-shadow: 0 0 24px 0 rgba(0, 0, 0, 0.12);\n");
      out.write("  padding: 30px;\n");
      out.write("  background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .form-group {\n");
      out.write("  padding-bottom: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .validate {\n");
      out.write("  display: none;\n");
      out.write("  color: red;\n");
      out.write("  margin: 0 0 15px 0;\n");
      out.write("  font-weight: 400;\n");
      out.write("  font-size: 13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .error-message {\n");
      out.write("  display: none;\n");
      out.write("  color: #fff;\n");
      out.write("  background: #ed3c0d;\n");
      out.write("  text-align: left;\n");
      out.write("  padding: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .error-message br + br {\n");
      out.write("  margin-top: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .sent-message {\n");
      out.write("  display: none;\n");
      out.write("  color: #fff;\n");
      out.write("  background: #18d26e;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 15px;\n");
      out.write("  font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .loading {\n");
      out.write("  display: none;\n");
      out.write("  background: #fff;\n");
      out.write("  text-align: center;\n");
      out.write("  padding: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact .loading:before {\n");
      out.write("  content: \"\";\n");
      out.write("  display: inline-block;\n");
      out.write("  border-radius: 50%;\n");
      out.write("  width: 24px;\n");
      out.write("  height: 24px;\n");
      out.write("  margin: 0 10px -6px 0;\n");
      out.write("  border: 3px solid #18d26e;\n");
      out.write("  border-top-color: #eee;\n");
      out.write("  -webkit-animation: animate-loading 1s linear infinite;\n");
      out.write("  animation: animate-loading 1s linear infinite;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact  input, .contact textarea {\n");
      out.write("  border-radius: 0;\n");
      out.write("  box-shadow: none;\n");
      out.write("  font-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact input {\n");
      out.write("  height: 44px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact textarea {\n");
      out.write("  padding: 10px 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact button[type=\"submit\"] {\n");
      out.write("  background: #01b1d7;\n");
      out.write("  border: 0;\n");
      out.write("  padding: 10px 24px;\n");
      out.write("  color: #fff;\n");
      out.write("  transition: 0.4s;\n");
      out.write("  border-radius: 4px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact  button[type=\"submit\"]:hover {\n");
      out.write("  background: #0dd3fe;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".contact  button{\n");
      out.write("  background: #01b1d7;\n");
      out.write("  border: 0;\n");
      out.write("  padding: 10px 24px;\n");
      out.write("  color: #fff;\n");
      out.write("  transition: 0.4s;\n");
      out.write("  border-radius: 4px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- ======= Top Bar ======= -->\n");
      out.write("\t<section id=\"topbar\" class=\"d-none d-lg-block\">\n");
      out.write("\t\t<div class=\"container d-flex\">\n");
      out.write("\t\t\t<div class=\"contact-info mr-auto\">\n");
      out.write("\t\t\t\t<i class=\"icofont-envelope\"></i><a href=\"mailto:contact@example.com\">chk4814@naver.com</a>\n");
      out.write("\t\t\t\t<i class=\"icofont-phone phone-icon\"></i> +1 5589 55488 55\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\n");
      out.write("\t\t\t\t<a href=\"/login/login_form.jsp\">LOGIN</a> <a\n");
      out.write("\t\t\t\t\thref=\"/join/join_form.jsp\">JOIN</a>\n");
      out.write("\t\t\t\t");

      	}
      	else
      	{
    	  
      out.write("\n");
      out.write("\t\t\t\t<a href=\"/login/logout_action.jsp\">LOGOUT</a> <a\n");
      out.write("\t\t\t\t\thref=\"/mypage/mypage.jsp\">MYPAGE</a>\n");
      out.write("\t\t\t\t");

      	}
      
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\t<!-- ======= Header ======= -->\n");
      out.write("\t<header id=\"header\" class=\"d-flex align-items-center\">\n");
      out.write("\t\t<div class=\"container d-flex align-items-center\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"logo mr-auto\">\n");
      out.write("\t\t\t\t<h1 class=\"text-light\">\n");
      out.write("\t\t\t\t\t<a href=\"/index.jsp\">Easy<span>ET</span></a>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t\t<!-- Uncomment below if you prefer to use an image logo -->\n");
      out.write("\t\t\t\t<!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<nav class=\"nav-menu d-none d-lg-block\">\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/health/health.jsp\">건강정보</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"drop-down\"><a href=\"\">Board</a>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/board/board_list.jsp\">소통게시판</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<!-- .nav-menu -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- End Header -->\n");
      out.write("\n");
      out.write("\t<main id=\"main\">\n");
      out.write("\t\t<!-- 여기 코딩 -->\n");
      out.write("\t\t<div class=\"container contact\">\n");
      out.write("\t\t\t<div class=\"row content\">\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-sm-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-md-8 col-sm-12\" style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t<h1 align=\"center\">소통게시판</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t\t");

					if(session.getAttribute("ss") != null)
					{
				
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-8 col-sm-12\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"board_insert_form.jsp?pg=");
      out.print(pg);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-default\" style=\"align:right;\">글 작성하기</button></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\t\t\t\t<br>\n");
      out.write("\t\t\t\t<div class=\"row content\">\n");
      out.write("\t\t\t\t\t<table class=\"table table-hover table-striped\">\n");
      out.write("\t\t\t\t\t\t<tr\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-weight: bold; font-size: 15px; text-align: center; border-top: 2px solid #b0b0b0; border-bottom: 2px solid #b0b0b0; height: 40px;\">\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 7%\">No</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 30%\">제목</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 9%\">댓글</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 9%\">추천</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 18%\">작성자</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 19%\">작성일</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 8%\">조회수</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t");

						PreparedStatement pstmt=null;
						ResultSet rs = null;
						ResultSet rs1 = null;
						ResultSet rs2 = null;
						
						String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
						String dbId="yhpj";
						String dbPass="Yuhan2020!";
						
						int total = 0;
		
						try{
							Class.forName("com.mysql.jdbc.Driver"); 
							Connection conn = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
					
							String count = "SELECT COUNT(*) FROM board";
							pstmt = conn.prepareStatement(count);
							rs= pstmt.executeQuery();
							
							if(rs.next())
							{
								total = rs.getInt(1);
							}
							
							allPage = (int)Math.ceil(total/(double)ROWSIZE);
							
							if(endPage > allPage) {
								endPage = allPage;
							}
						
							//String BoardSQL="SELECT * FROM board WHERE board_uid >= "+ start +" AND board_uid <= " +end + " ORDER BY board_uid DESC";
							String BoardSQL="SELECT * FROM board WHERE board_uid >= "+ start +" AND board_uid <= " +end + " ORDER BY board_uid DESC";
							
							pstmt = conn.prepareStatement(BoardSQL);
							rs = pstmt.executeQuery();
							
							while(rs.next())
							{	
								String Board_Uid = rs.getString("board_uid");
								String Board_Title = rs.getString("board_title");
								String Board_Writer = rs.getString("board_writer");
								String Board_Date = rs.getString("board_date");
								String Board_Look_Cnt = rs.getString("board_look_cnt");
								String Board_Reply_Cnt = rs.getString("board_reply_cnt");
								String Board_Good_Cnt = rs.getString("board_good_cnt");
								
								Date date = new Date(); 
								SimpleDateFormat simpleDate = new SimpleDateFormat("yyyy-MM-dd"); 
								String year = (String)simpleDate.format(date); 
								String yea = Board_Date.substring(0,10);
					
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<tr style=\"text-align: center;\" class=\"content\">\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 7%\">");
      out.print(Board_Uid);
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"text-align: left; width: 30%;\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"board_detail_form.jsp?boardid=");
      out.print( Board_Uid );
      out.write("&pg=");
      out.print(pg);
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( Board_Title );
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t</a> \n");
      out.write("\t\t\t\t\t\t\t");

								if(year.equals(yea)){
								
      out.write(" &nbsp;<img src='./BoardIcon/Icon_New.png' width=\"10\" /> ");

								}  
							
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 9%\"><img src='./BoardIcon/Icon_Reply.png' />\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( Board_Reply_Cnt );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 9%\"><img src='./BoardIcon/Icon_Good.png' />\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print( Board_Good_Cnt );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t");

							
								try{
									Class.forName("com.mysql.jdbc.Driver"); 
									Connection conn2 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
							
									String sql = "SELECT name name1, Max(weight), Min(weight), Max(skeletal_muscle_mass), Min(skeletal_muscle_mass), check_date FROM inbody " + 
									             "WHERE month(now()) = month(check_date) GROUP by name order by Max(skeletal_muscle_mass)-Min(skeletal_muscle_mass) DESC limit 1";
									pstmt = conn2.prepareStatement(sql);
									
									rs1= pstmt.executeQuery();
									
									while(rs1.next())
									{	
										String name1 = rs1.getString("name1");
										
										String sql2 = "SELECT name, Max(weight), Min(weight), Max(skeletal_muscle_mass), Min(skeletal_muscle_mass), check_date FROM inbody " + 
										              "WHERE month(now()) = month(check_date) group by name  order by Max(weight)-Min(weight) DESC limit 1"; 
										pstmt = conn2.prepareStatement(sql2);
										
										rs2= pstmt.executeQuery();
										
										while(rs2.next())
										{	
											String name2 = rs2.getString("name");
													
								if(name1.equals(Board_Writer) || name2.equals(Board_Writer)) //여기 수정하기
								{
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"icofont-crown\">");
      out.print( Board_Writer );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 18%\">");
      out.print( Board_Writer );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t");

										}
										}
									}
									rs2.close();
									rs1.close();
									conn2.close();
								
							
								}catch(ClassNotFoundException e){
									out.println("Where is your mysql jdbc driver?");
									e.printStackTrace();
									//return;
								}
				
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 19%\">");
      out.print( Board_Date );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t<td style=\"width: 8%\">");
      out.print( Board_Look_Cnt );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t");

							} 
      out.write("\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"7\" align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t");

								if(pg>BLOCK) {
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_list.jsp?pg=1\" class=\"btn btn-default\" style=\"background-color: gray;\">&laquo;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_list.jsp?pg=");
      out.print(startPage-1);
      out.write("\" class=\"btn btn-default\" style=\"background-color: gray;\">&lt;</a>\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");

								for(int i=startPage; i<= endPage; i++){
									if(i==pg){
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_list.jsp?pg=");
      out.print(i );
      out.write("\" class=\"btn btn-default\" style=\"background-color: gray;\"><font color=\"white\">");
      out.print(i );
      out.write("</font></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}else{
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_list.jsp?pg=");
      out.print(i );
      out.write("\" class=\"btn btn-default\" style=\"background-color: gray;\"><font color=\"white\">");
      out.print(i );
      out.write("</font></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								if(endPage<allPage){
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_list.jsp?pg=");
      out.print(endPage+1);
      out.write("\">&gt;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"board_list.jsp?pg=");
      out.print(allPage);
      out.write("\">&raquo;</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"row\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t");

							
			conn.close();
			
		
			}catch(ClassNotFoundException e){
				out.println("Where is your mysql jdbc driver?");
				e.printStackTrace();
				//return;
			}
		
      out.write("\n");
      out.write("\t\t<!-- \t</section> -->\n");
      out.write("\t</main>\n");
      out.write("\n");
      out.write("\t<!-- End #main -->\n");
      out.write("\n");
      out.write("\t<!-- ======= Footer ======= -->\n");
      out.write("\t<footer id=\"footer\">\n");
      out.write("\t\t<div class=\"footer-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-md-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-info\">\n");
      out.write("\t\t\t\t\t\t\t<h3>EasyET</h3>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t경기도 부천시 경인로 590 <br> <strong>Phone:</strong> +82\n");
      out.write("\t\t\t\t\t\t\t\t02-2610-0600<br> <strong>Email:</strong> chk4814@naver.com<br>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-md-6 footer-links\">\n");
      out.write("\t\t\t\t\t\t<h4>사이트맵</h4>\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/index.jsp\">Home</a>&nbsp;&nbsp; <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/health/health.jsp\">건강정보</a>&nbsp;&nbsp; <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/honor/honor.jsp\">명예의 전당</a>&nbsp;&nbsp; <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/board/board_list.jsp\">소통게시판</a>&nbsp;&nbsp; <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/notice/notice_list.jsp\">공지사항</a>&nbsp;&nbsp;</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"copyright\">\n");
      out.write("\t\t\t\t&copy; Copyright <strong><span>MyBiz</span></strong>. All Rights\n");
      out.write("\t\t\t\tReserved\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"credits\">\n");
      out.write("\t\t\t\t<!-- All the links in the footer should remain intact. -->\n");
      out.write("\t\t\t\t<!-- You can delete the links only if you purchased the pro version. -->\n");
      out.write("\t\t\t\t<!-- Licensing information: https://bootstrapmade.com/license/ -->\n");
      out.write("\t\t\t\t<!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\n");
      out.write("\t\t\t\tDesigned by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- End Footer -->\n");
      out.write("\n");
      out.write("\t<a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\n");
      out.write("\n");
      out.write("\t<!-- Vendor JS Files -->\n");
      out.write("\t<script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/php-email-form/validate.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\n");
      out.write("\t<script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Template Main JS File -->\n");
      out.write("\t<script src=\"/assets/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
