/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-12-03 07:21:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.honor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class honor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \t\n");
      out.write("    <!DOCTYPE html>\n");
      out.write("<html lang=\"utf-8\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("\n");
      out.write("  <title>Honor Page</title>\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\n");
      out.write("  <meta content=\"\" name=\"keywords\">\n");
      out.write("\n");
      out.write("  <!-- Favicons -->\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("  <!-- Google Fonts -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Vendor CSS Files -->\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"/assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Template Main CSS File -->\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- =======================================================\n");
      out.write("  * Template Name: MyBiz - v2.1.0\n");
      out.write("  * Template URL: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/\n");
      out.write("  * Author: BootstrapMade.com\n");
      out.write("  * License: https://bootstrapmade.com/license/\n");
      out.write("  ======================================================== -->\n");
      out.write("  \n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- ======= Top Bar ======= -->\n");
      out.write("  <section id=\"topbar\" class=\"d-none d-lg-block\">\n");
      out.write("    <div class=\"container d-flex\">\n");
      out.write("      <div class=\"contact-info mr-auto\">\n");
      out.write("        <i class=\"icofont-envelope\"></i><a href=\"mailto:chk4814@naver.com \">chk4814@naver.com</a>\n");
      out.write("        <i class=\"icofont-phone phone-icon\"></i> +82 02-2610-0600\n");
      out.write("      </div>\n");
      out.write("      <div>\n");
      out.write("      \t ");

      	if(session.getAttribute("ss") == null)
      	{
    	  
      out.write("\n");
      out.write("    \t  \t<a href=\"/login/login_form.jsp\" >LOGIN</a> \n");
      out.write("      \t \t<a href=\"/join/join_form.jsp\" >JOIN</a>\n");
      out.write("    \t  ");

      	}
      	else
      	{
    	  
      out.write("\n");
      out.write("    \t  \t<a href=\"/login/logout_action.jsp\" >LOGOUT</a> \n");
      out.write("      \t \t<a href=\"/mypage/mypage.jsp\" >MYPAGE</a>\n");
      out.write("    \t  ");

      	}
      
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- ======= Header ======= -->\n");
      out.write("  <header id=\"header\" class=\"d-flex align-items-center\">\n");
      out.write("    <div class=\"container d-flex align-items-center\">\n");
      out.write("\n");
      out.write("      <div class=\"logo mr-auto\">\n");
      out.write("        <h1 class=\"text-light\"><a href=\"/index.jsp\">Easy<span>ET</span></a></h1>\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\n");
      out.write("        <!-- <a href=\"index.html\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block\">\n");
      out.write("        <ul>\n");
      out.write("          <li class=\"active\"><a href=\"/index.jsp\">Home</a></li>\n");
      out.write("          <li><a href=\"/health/health.jsp\">건강정보</a></li>\n");
      out.write("          <li><a href=\"/honor/honor.jsp\">명예의 전당</a></li>\n");
      out.write("          <li class=\"drop-down\"><a href=\"\">Board</a>\n");
      out.write("          \t<ul>\n");
      out.write("          \t\t<li><a href=\"/board/board_list.jsp\">게시판</a></li>\n");
      out.write("          \t\t<li><a href=\"/notice/notice_list.jsp\">공지사항</a></li>\n");
      out.write("          \t</ul>\n");
      out.write("        </ul>\n");
      out.write("      </nav><!-- .nav-menu -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </header><!-- End Header -->\n");
      out.write("\n");
      out.write("  <main id=\"main\">\n");
      out.write("  \t<!-- 여기다 코딩 -->\n");
      out.write("  \t<br>\n");
      out.write("\n");

  	if(session.getAttribute("ss") == null)
      {
      	
      out.write("\n");
      out.write("    \t \t<div class=\"container contact\">\n");
      out.write("  \t\t\t\t<div class=\"row content\">\n");
      out.write("  \t\t\t\t\t<div class=\"col-lg-6\">\n");
      out.write("  \t\t\t\t\t\t<h2>로그인 안내</h2>\n");
      out.write("  \t\t\t\t\t\t<h4>명예의 전당을 이용하려면 로그인이 필요합니다.<br><a href=\"/login/login_form.jsp\">로그인하러 가기</a></h4>\n");
      out.write("  \t\t\t\t\t</div>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("  \t\t\t</div>\n");
      out.write("    \t");

      }
      else
      {
  		
      out.write("\n");
      out.write("      \n");
      out.write("\t  <section id=\"services\" class=\"services section-bg\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">\n");
      out.write("          <span>Honor</span>\n");
      out.write("          <h2>Honor</h2>\n");
      out.write("          <p>이번 달 명예의 전당</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("\t\t<div class=\"col-md-12\">\n");
      out.write("            <div class=\"icon-box\">\n");
      out.write("              <i class=\"icofont-measure\"></i>\n");
      out.write("              <h4><a href=\"#\">체중 감량 순</a></h4> <br>\n");
      out.write("              \t<table class=\"table table-hover table-striped\">\n");
      out.write("              \t\t\t<tr>\n");
      out.write("              \t\t\t\t<td style=\"width: 1%\"> </td>\n");
      out.write("\t\t\t\t\t\t\t<td>등수 </td>\n");
      out.write("\t\t\t        \t\t<td>아이디</td>\n");
      out.write("\t\t\t        \t\t<td>감량한 체중</td>\n");
      out.write("\t\t\t        \t\t<td>증가한 골격근량</td>\n");
      out.write("\t\t\t        \t</tr>\n");
      out.write("              \t");

			Connection conn = null;
			PreparedStatement pstmt = null;
			String str = "";
			ResultSet rs = null;
			
			String name = null;
			float Max_weight = 0;
			float Min_weight = 0;
			float Max_skeletal_muscle_mass = 0;
			float Min_skeletal_muscle_mass = 0;
			String check_date;
			int rank = 0;
			
			try{
				String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
				String dbId = "yhpj";
				String dbPass = "Yuhan2020!";
				
				Class.forName ("com.mysql.jdbc.Driver"); //driver load
				conn = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
				
				String sql = "SELECT name, Max(weight), Min(weight), Max(skeletal_muscle_mass), Min(skeletal_muscle_mass), check_date FROM inbody " + 
							 "WHERE month(now()) = month(check_date) group by name  order by Max(weight)-Min(weight) DESC";
				
				/* String sql = "SELECT name, Max(weight), Min(weight), Max(skeletal_muscle_mass), Min(skeletal_muscle_mass), check_date, "+
						"(SELECT COUNT(*)+1 FROM inbody group by name having Max(weight)-Min(weight) > Max(i.weight)-Min(i.weight)) "+
						"FROM inbody i group by name having month(now()) = month(check_date) order by Max(weight)-Min(weight) desc "; */
				pstmt = conn.prepareStatement(sql);
				rs = pstmt.executeQuery();
				
				while(rs.next())
			 	{
			 		name = rs.getString(1);
					Max_weight = rs.getFloat(2);
					Min_weight = rs.getFloat(3);
					Max_skeletal_muscle_mass = rs.getFloat(4);
					Min_skeletal_muscle_mass = rs.getFloat(5);
					check_date = rs.getString(6);
					
			
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t        \t");
      out.write("\n");
      out.write("\t\t\t        \t<tr>\n");
      out.write("\t\t\t        \t");
  if(rank == 0) { rank++; 
      out.write("\n");
      out.write("\t\t        \t\t\t<td class=\"icofont-crown\"> </td>\n");
      out.write("\t\t        \t\t\t<td> ");
      out.print(rank );
      out.write("등 </td>\n");
      out.write("\t\t\t        \t");
	
			        	    }
			        		else if(rank >= 1 && rank < 5) { rank++; 
      out.write("\n");
      out.write("\t\t\t        \t\t<td> </td>\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(rank );
      out.write("등</td>\n");
      out.write("\t\t\t        \t");

			        		}
			        		else if(rank == 5){
			        		  break;
			        	    }
			        	
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(name );
      out.write("</td>\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(Max_weight - Min_weight );
      out.write("kg</td>\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(Max_skeletal_muscle_mass - Min_skeletal_muscle_mass );
      out.write("kg</td>\n");
      out.write("\t\t\t        \t</tr>\n");
      out.write("\t\t\t");
  				 
							/*  }else break;
							} */
				 }
			
			}catch(Exception e){
				e.printStackTrace();
			}finally{
				if(rs !=null)
					try{rs.close();}catch(SQLException sqle){}
				if(pstmt != null)
					try{pstmt.close();}catch(SQLException sqle){}
				if(conn != null)
					try{conn.close();}catch(SQLException sqle){}
			}
			
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t</div></table><br>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            \n");
      out.write("\t        <br>\n");
      out.write("\t        <div class=\"col-md-13\">\n");
      out.write("            <div class=\"icon-box\">\n");
      out.write("              <i class=\"icofont-muscle-weight\"></i>\n");
      out.write("              <h4><a href=\"#\">골격근량 증가 순</a></h4> <br>\n");
      out.write("              \t<table class=\"table table-hover table-striped\">\n");
      out.write("              \t\t\t<tr>\n");
      out.write("              \t\t\t\t<td style=\"width: 1%\"> </td>\n");
      out.write("\t\t\t\t\t\t\t<td>등수 </td>\n");
      out.write("\t\t\t        \t\t<td>아이디</td>\n");
      out.write("\t\t\t        \t\t<td>증가한 골격근량</td>\n");
      out.write("\t\t\t        \t\t<td>감량한 체중</td>\n");
      out.write("\t\t\t        \t</tr>\n");
      out.write("              \t");

			Connection conn2 = null;
			PreparedStatement pstmt2 = null;
			String str2 = "";
			ResultSet rs2 = null;
			
			String name2 = null;
			float Max_weight2 = 0;
			float Min_weight2 = 0;
			float Max_skeletal_muscle_mass2 = 0;
			float Min_skeletal_muscle_mass2 = 0;
			String check_date2;
			int rank2 = 0;
			
			try{
				String jdbcUrl = "jdbc:mysql://localhost:3306/yhpj";
				String dbId = "yhpj";
				String dbPass = "Yuhan2020!";
				
				Class.forName ("com.mysql.jdbc.Driver"); //driver load
				conn2 = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
				
				String sql2 = "SELECT name, Max(weight), Min(weight), Max(skeletal_muscle_mass), Min(skeletal_muscle_mass), check_date FROM inbody " +
						      "WHERE month(now()) = month(check_date) GROUP by name order by Max(skeletal_muscle_mass)-Min(skeletal_muscle_mass) desc";
				
				pstmt2 = conn2.prepareStatement(sql2);
				rs2 = pstmt2.executeQuery();
				
				while(rs2.next())
			 	{
			 		name2 = rs2.getString(1);
					Max_weight2 = rs2.getFloat(2);
					Min_weight2 = rs2.getFloat(3);
					Max_skeletal_muscle_mass2 = rs2.getFloat(4);
					Min_skeletal_muscle_mass2 = rs2.getFloat(5);
					check_date2 = rs2.getString(6);
					
			
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t        \t\n");
      out.write("\t\t\t        \t<tr>\n");
      out.write("\t\t\t\t\t\t\t");
  if(rank2 == 0) { rank2++; 
      out.write("\n");
      out.write("\t\t        \t\t\t<td class=\"icofont-crown\"> </td>\n");
      out.write("\t\t        \t\t\t<td> ");
      out.print(rank2 );
      out.write("등 </td>\n");
      out.write("\t\t\t        \t");
	
			        	    }
			        		else if(rank2 >= 1 && rank2 < 5) { rank2++; 
      out.write("\n");
      out.write("\t\t\t        \t\t<td> </td>\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(rank2 );
      out.write("등</td>\n");
      out.write("\t\t\t        \t");

			        		}
			        		else if(rank == 5){
				        		  break;
			        	    }
			        	
      out.write("\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(name2 );
      out.write("</td>\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(Max_skeletal_muscle_mass2 - Min_skeletal_muscle_mass2 );
      out.write("kg</td>\n");
      out.write("\t\t\t        \t\t<td>");
      out.print(Max_weight2 - Min_weight2 );
      out.write("kg</td>\n");
      out.write("\t\t\t        \t</tr>\n");
      out.write("\t\t\t");
  				 
							
				 }
			
			}catch(Exception e){
				e.printStackTrace();
			}finally{
				if(rs2 !=null)
					try{rs2.close();}catch(SQLException sqle){}
				if(pstmt2 != null)
					try{pstmt2.close();}catch(SQLException sqle){}
				if(conn2 != null)
					try{conn2.close();}catch(SQLException sqle){}
			}
			
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t        \t\n");
      out.write("\t\t\t        </table><br>\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t        </form>\n");
      out.write("\t\t        \n");
      out.write("\t");

		} 

      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        \n");
      out.write("          ");
      out.write("\n");
      out.write("  \t\n");
      out.write("  </main><!-- End #main -->\n");
      out.write("\n");
      out.write("  <!-- ======= Footer ======= -->\n");
      out.write("  <footer id=\"footer\">\n");
      out.write("    <div class=\"footer-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-6 col-md-6\">\n");
      out.write("            <div class=\"footer-info\">\n");
      out.write("              <h3>EasyET</h3>\n");
      out.write("              <p>\n");
      out.write("                                    경기도 부천시 경인로 590 <br>\n");
      out.write("                <strong>Phone:</strong> +82 02-2610-0600<br>\n");
      out.write("                <strong>Email:</strong> chk4814@naver.com<br>\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-6 col-md-6 footer-links\">\n");
      out.write("            <h4>사이트맵</h4>\n");
      out.write("            <ul>\n");
      out.write("              <li>\n");
      out.write("              \t<a href=\"/index.jsp\">Home</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/health/health.jsp\">건강정보</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/honor/honor.jsp\">명예의 전당</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/board/board_list.jsp\">게시판</a>&nbsp&nbsp\n");
      out.write("              \t<a href=\"/notice/notice_list.jsp\">공지사항</a>&nbsp&nbsp\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"copyright\">\n");
      out.write("        &copy; Copyright <strong><span>MyBiz</span></strong>. All Rights Reserved\n");
      out.write("      </div>\n");
      out.write("      <div class=\"credits\">\n");
      out.write("        <!-- All the links in the footer should remain intact. -->\n");
      out.write("        <!-- You can delete the links only if you purchased the pro version. -->\n");
      out.write("        <!-- Licensing information: https://bootstrapmade.com/license/ -->\n");
      out.write("        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mybiz-free-business-bootstrap-theme/ -->\n");
      out.write("        Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer><!-- End Footer -->\n");
      out.write("\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\n");
      out.write("\n");
      out.write("  <!-- Vendor JS Files -->\n");
      out.write("  <script src=\"/assets/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/jquery-sticky/jquery.sticky.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/counterup/counterup.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/venobox/venobox.min.js\"></script>\n");
      out.write("  <script src=\"/assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Template Main JS File -->\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
